In [17]:
from scircuit import *
import numpy as np

In [18]:
#Define the circuit
C = Capacitor(value = 0.5, unit='F')
L1 = Inductor(value = 0.5, unit = 'H')
L2 = Inductor(value = 0.5, unit = 'H')
L3 = Inductor(value = 0.5, unit = 'H')
elements1 = [(0,1,C), (0,1,L1)] 
elements2 = [(0,2,C), (0,1,L1), (1,2,L2)] 
elements3 = [(0,2,C), (0,2,L3), (0,1,L1), (1,2,L2)]
elements4 = [(0,1,C), (0,1,L1), (0,1,L2)] 
starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L1), (1,3,L1), (2,3,L1)]

cr = Circuit(starcircuit)

In [19]:
# Calculate omega_2B 
omega_2B = cr.omega_2B
print(f"The matrix expression for omega_2B is:\n{omega_2B}")

# Calculate omega
omega = cr.omega_canonical
print(f"The matrix expression for omega is:\n{cr.omega_canonical}")
print(f"The matrix variable change for omega is:\n{cr.canonical_basis_change}")
print(f"The determinant of matrix omega is:\n{np.linalg.det(omega)}")

The matrix expression for omega_2B is:
[[ 0.   0.   0.   0.   0.   0.   0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.  -0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5]
 [-0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.5  0.   0.   0.   0.   0.   0. ]]
The matrix expression for omega is:
[[ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [-1. -0.  0.  0.  0.  0.]
 [-0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
The m

In [20]:
np.set_printoptions(precision=3)

# Calculate the Hamiltonian matrix before the variable change
hamiltonian_2B = cr.hamiltonian_2B
print(f"The matrix expression for the H before the variable change is:\n{hamiltonian_2B}")

# Calculate the Hamiltonian matrix after the variable change
hamiltonian = cr.hamiltonian
print(f"The matrix expression for the H after the variable change is:\n{hamiltonian}")

The matrix expression for the H before the variable change is:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
The matrix expression for the H after the variable change is:
[[ 3.  1.  2.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.]
 [ 2.  1.  2.  0.  0.  0.]
 [ 0.  0.  0.  2.  1. -2.]
 [ 0.  0.  0.  1.  1. -1.]
 [ 0.  0.  0. -2. -1.  3.]]
