In [19]:
from scircuit import *
import numpy as np

In [20]:
#Define the circuit
C = Capacitor(value = 1, unit='GHz')
Cg = Capacitor(value = 1, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
L2 = Inductor(value = 1, unit = 'GHz')
L3 = Inductor(value = 3, unit = 'GHz')
elements1 = [(0,1,C), (0,1,L1)] 
elements2 = [(0,2,C), (0,1,L1), (1,2,L2)] 
elements3 = [(0,2,C), (0,2,L1), (0,1,L2), (1,2,L3)]
elements4 = [(0,1,C), (0,1,L1), (0,1,L2)] 
elements5 = [(0,3,C), (0,3,L1), (0,1,L2), (1,2,C), (2,3,L1)]
starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L1), (1,3,L1), (2,3,L1)]
starcircuit_4 = [(0,1,C), (1,2,C), (2,3,C), (3,0,C), (0,4,L1), (1,4,L1), (2,4,L1), (3,4,L1)]
starcircuit_nonsymmetric = [(0,1,C), (1,2,C), (2,0,C), (0,3,L2), (1,3,L1), (2,3,L1)]
#coupled_oscillators = [(0,1,C), (0,1,L1), (1,2,Cg), (2,0,C), (2,0,L1)]
coupled_oscillators = [(0,1,L1), (1,2,C), (2,0,L1), (0,1,C), (2,0,C)]

cr = Circuit(coupled_oscillators)


In [21]:
# Calculate omega_2B 
E_2B = cr.omega_2B
print(f"The matrix expression for omega_2B is:\n{E_2B}")

# Calculate omega
E = cr.omega_symplectic
print(f"The matrix expression for omega is:\n{cr.omega_symplectic}")
print(f"The matrix variable change for omega is:\n{cr.symplectic_basis_change}")
print(f"The determinant of matrix omega is:\n{np.linalg.det(E)}")

The matrix expression for omega_2B is:
[[ 0.   0.   0.   0.   0.  -0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.5]
 [ 0.5  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.5  0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -0.5  0.   0.   0.   0.   0. ]]
The matrix expression for omega is:
[[ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [-1. -0.  0.  0.]
 [-0. -1.  0.  0.]]
The matrix variable change for omega is:
[[ 1.000e+00 -0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00 -5.946e-01  0.000e+00 -8.395e-17  7.071e-01]
 [ 0.000e+00  5.946e-01 -0.000e+00 -2.053e-16  7.071e-01]
 [ 0.000e+00 -0.000e+00 -0.000e+00 -8.409e-01 -1.590e-16]
 [ 0.000e+00 -0.000e+00  1.000e+00  0.000e+0

In [22]:
np.set_printoptions(precision=3)

# Calculate the Hamiltonian matrix before the variable change
Total_energy_2B = cr.Total_energy_2B
print(f"The matrix expression for the H before the variable change is:\n{Total_energy_2B}")

# Calculate the Hamiltonian matrix in the same basis as E_canonical
Total_energy_symplectic_basis = cr.Total_energy_symplectic_basis
print(f"The matrix expression for the H in the same basis as E_canonical is:\n{Total_energy_symplectic_basis}")

# Calculate the final expression for the Hamiltonian matrix, hamiltonian_xi
hamiltonian = cr.classical_hamiltonian
hamiltonian_prueba = hamiltonian.copy()

print(cr.omega_symplectic)

eigenval,_ = np.linalg.eig(cr.omega_symplectic @ hamiltonian)

print("eig:", eigenval)

print(f"The final matrix expression for the H is:\n{hamiltonian}")



The matrix expression for the H before the variable change is:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
The matrix expression for the H in the same basis as E_canonical is:
[[ 1.000e+00  5.946e-01  0.000e+00 -2.053e-16  7.071e-01]
 [ 5.946e-01  1.061e+00  0.000e+00 -1.943e-16  4.204e-01]
 [ 0.000e+00  0.000e+00  1.000e+00 -8.409e-01 -1.590e-16]
 [-2.053e-16 -1.943e-16 -8.409e-01  1.414e+00 -8.233e-17]
 [ 7.071e-01  4.204e-01 -1.590e-16 -8.233e-17  1.500e+00]]
[[ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [-1. -0.  0.  0.]
 [-0. -1.  0.  0.]]
eig: [ 5.188e-18+0.577j  5.188e-18-0.577j -6.123e-17+1.j    -6.123e-17-1.j   ]
The final matrix expression for the H is:
[[ 6.667e-01  3.964e-01  7.496e-17 -1.665e-16]
 

In [23]:
from scircuit.algebra import *

H_n, T = canonical_transformation_quadratic_quantum_hamiltonian(hamiltonian)

print("Canonical Hamiltonian")
print(H_n)

print("Basis change matrix, T")
print(T)


Canonical Hamiltonian
[[ 5.774e-01 -1.611e-16 -2.406e-17 -1.303e-16]
 [-1.961e-16  1.000e+00 -5.485e-17 -7.218e-17]
 [-2.406e-17 -5.485e-17  5.774e-01 -3.910e-16]
 [-1.303e-16 -7.218e-17 -2.661e-16  1.000e+00]]
Basis change matrix, T
[[-9.306e-01  7.071e-01  0.000e+00  0.000e+00]
 [ 8.273e-16 -1.189e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00 -1.075e+00 -6.375e-16]
 [ 0.000e+00  0.000e+00 -6.389e-01 -8.409e-01]]


In [24]:
quantum_hamiltonian = cr.quantum_hamiltonian
np.set_printoptions(precision=3)
print("Quantum Hamiltonian")
print(quantum_hamiltonian)

Quantum Hamiltonian
[[ 5.774e-01+0.000e+00j -2.761e-16-3.774e-17j  5.551e-17-2.406e-17j -1.150e-16-9.258e-17j]
 [-2.311e-16+3.774e-17j  1.000e+00+0.000e+00j -3.499e-17-9.258e-17j  0.000e+00-7.218e-17j]
 [ 5.551e-17+2.406e-17j -1.150e-16+9.258e-17j  5.774e-01+0.000e+00j -2.761e-16+3.774e-17j]
 [-3.499e-17+9.258e-17j  0.000e+00+7.218e-17j -2.311e-16-3.774e-17j  1.000e+00+0.000e+00j]]


In [25]:
#np.set_printoptions(precision=3)
print("T inverse")
print(np.linalg.inv(T))

print("T transpose")
print(T.T)



T inverse
[[-1.075e+00 -6.389e-01 -0.000e+00 -0.000e+00]
 [-7.476e-16 -8.409e-01 -0.000e+00 -0.000e+00]
 [-0.000e+00 -0.000e+00 -9.306e-01  7.055e-16]
 [-0.000e+00 -0.000e+00  7.071e-01 -1.189e+00]]
T transpose
[[-9.306e-01  8.273e-16  0.000e+00  0.000e+00]
 [ 7.071e-01 -1.189e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00 -1.075e+00 -6.389e-01]
 [ 0.000e+00  0.000e+00 -6.375e-16 -8.409e-01]]


In [26]:
# COUPLED OSCILLATORS
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 1, unit='GHz')
C2 = Capacitor(value = 1, unit='GHz')
Cg = Capacitor(value = 1, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
L2 = Inductor(value = 1, unit = 'GHz')

coupled_oscillators = [(0,1,L1), (1,2,Cg), (2,0,L1), (0,1,C1),(2,0,C1)]

cr = Circuit(coupled_oscillators)
co_hamiltonian = cr.classical_hamiltonian

H_n_co, T = canonical_transformation_quadratic_quantum_hamiltonian(co_hamiltonian)
print("Matriz cambio de base T:")
print(T)
print("Hamiltoniano canónico:")
print(H_n_co)

Matriz cambio de base T:
[[-9.306e-01  7.071e-01  0.000e+00  0.000e+00]
 [ 8.273e-16 -1.189e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00 -1.075e+00 -6.375e-16]
 [ 0.000e+00  0.000e+00 -6.389e-01 -8.409e-01]]
Hamiltoniano canónico:
[[ 5.774e-01 -1.611e-16 -2.406e-17 -1.303e-16]
 [-1.961e-16  1.000e+00 -5.485e-17 -7.218e-17]
 [-2.406e-17 -5.485e-17  5.774e-01 -3.910e-16]
 [-1.303e-16 -7.218e-17 -2.661e-16  1.000e+00]]


In [27]:
# COUPLED OSCILLATORS -> Adrian's tests
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 1, unit='GHz')
C2 = Capacitor(value = 1, unit='GHz')
Cg = Capacitor(value = 2, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
L2 = Inductor(value = 1, unit = 'GHz')
Lg = Inductor(value = 2, unit = 'GHz')

coupled_oscillators1 = [(0,1,L1), (1,2,Lg), (2,0,L2), (0,1,C1), (1,2,Cg),(2,0,C2)]
coupled_oscillators2 = [(0,1,L1), (2,0,L2), (0,1,C1), (1,2,Cg), (2,0,C2)]
coupled_oscillators3 = [(0,1,L1), (2,0,L2), (0,1,C1), (2,0,C2)]

cr = Circuit(coupled_oscillators2)
co_hamiltonian = cr.classical_hamiltonian

H_n_co, T = canonical_transformation_quadratic_quantum_hamiltonian(co_hamiltonian)

print("Hamiltoniano canónico:")
print(H_n_co)


# segun adrian tiene que ser 1 y 0.6

Hamiltoniano canónico:
[[ 7.071e-01  1.527e-32  3.786e-17  1.218e-17]
 [ 1.341e-32  1.000e+00 -3.374e-17 -1.120e-16]
 [ 3.786e-17 -3.374e-17  7.071e-01 -1.233e-32]
 [ 1.218e-17 -1.120e-16 -6.987e-33  1.000e+00]]


In [28]:
# CHECKS CON ADRIAN
np.set_printoptions(linewidth=150, threshold=np.inf)

C = Capacitor(value = 1, unit='GHz')
L = Inductor(value = 1, unit = 'GHz')

# 2 C Y 1 L en paralelo
check1 = [(0,1,C),(0,1,C),(0,1,L)]
cr = Circuit(check1)
hamiltonian = cr.classical_hamiltonian

H_n, T = canonical_transformation_quadratic_quantum_hamiltonian(hamiltonian)
print("Hamiltoniano canónico:")
print(H_n)

# 2 C Y 1 L en serie
check2 = [(0,1,C),(1,2,C),(2,0,L)]
cr = Circuit(check2)
hamiltonian = cr.classical_hamiltonian

H_n, T = canonical_transformation_quadratic_quantum_hamiltonian(hamiltonian)
print("Hamiltoniano canónico:")
print(H_n)

# 1 C Y 2 L en serie
check3 = [(0,1,C),(1,2,L),(2,0,L)]
cr = Circuit(check3)
hamiltonian = cr.classical_hamiltonian

H_n, T = canonical_transformation_quadratic_quantum_hamiltonian(hamiltonian)
print("Hamiltoniano canónico:")
print(H_n)

# 1 C Y 2 L en paralelo
check4 = [(0,1,C),(0,1,L),(0,1,L)]
cr = Circuit(check4)
hamiltonian = cr.classical_hamiltonian

H_n, T = canonical_transformation_quadratic_quantum_hamiltonian(hamiltonian)
print("Hamiltoniano canónico:")
print(H_n)

Hamiltoniano canónico:
[[0.707 0.   ]
 [0.    0.707]]
Hamiltoniano canónico:
[[1.414 0.   ]
 [0.    1.414]]
Hamiltoniano canónico:
[[0.707 0.   ]
 [0.    0.707]]
Hamiltoniano canónico:
[[ 1.414e+00 -1.614e-17]
 [-1.614e-17  1.414e+00]]


In [29]:
#SYMMETRIC STAR CIRCUIT 
np.set_printoptions(linewidth=150, threshold=np.inf)

cr = Circuit(starcircuit)
sc_hamiltonian = cr.classical_hamiltonian

H_n_sc, T = canonical_transformation_quadratic_quantum_hamiltonian(sc_hamiltonian)
print("Matriz cambio de base T:")
print(T)
print("Hamiltoniano canónico:")
print(H_n_sc)


Matriz cambio de base T:
[[-1.006 -0.144  0.     0.   ]
 [ 0.112  1.01   0.     0.   ]
 [ 0.     0.    -1.01   0.112]
 [ 0.     0.    -0.144  1.006]]
Hamiltoniano canónico:
[[ 5.774e-01 -1.178e-16 -1.270e-16  2.201e-18]
 [-2.044e-16  5.774e-01  4.409e-17  2.750e-17]
 [-1.270e-16  4.409e-17  5.774e-01 -5.057e-16]
 [ 2.201e-18  2.750e-17 -2.299e-16  5.774e-01]]


In [30]:
#SYMMETRIC SQUARE CIRCUIT 
np.set_printoptions(linewidth=150, threshold=np.inf)

cr = Circuit(starcircuit_4)
sc4_hamiltonian = cr.classical_hamiltonian

H_n_sc4, T = canonical_transformation_quadratic_quantum_hamiltonian(sc4_hamiltonian)
print("Matriz cambio de base T:")
print(T)
print("Hamiltoniano canónico:")
print(H_n_sc4)

Matriz cambio de base T:
[[ 0.502  0.     0.906  0.     0.     0.   ]
 [ 0.115  0.963  0.366  0.     0.     0.   ]
 [ 0.872  0.127 -0.473  0.     0.     0.   ]
 [ 0.     0.     0.     0.502 -0.374  0.825]
 [ 0.     0.     0.    -0.115  1.028  0.064]
 [ 0.     0.    -0.     0.872  0.079 -0.484]]
Hamiltoniano canónico:
[[ 5.000e-01  4.556e-15  5.057e-15  9.197e-17 -2.802e-17  6.750e-17]
 [ 4.514e-15  7.071e-01 -3.374e-16 -4.336e-17 -3.868e-17  1.242e-16]
 [ 5.007e-15 -4.578e-16  7.071e-01  4.698e-17  1.245e-16 -1.309e-16]
 [ 9.197e-17 -4.336e-17  4.698e-17  5.000e-01  6.259e-15  6.978e-15]
 [-2.802e-17 -3.868e-17  1.245e-16  6.285e-15  7.071e-01  2.033e-16]
 [ 6.750e-17  1.242e-16 -1.309e-16  6.771e-15  5.411e-16  7.071e-01]]


In [31]:
# NO-SYMMETRIC STAR CIRCUIT
np.set_printoptions(linewidth=150, threshold=np.inf)


cr = Circuit(starcircuit_nonsymmetric)
scns_hamiltonian = cr.classical_hamiltonian

H_n_scns, T = canonical_transformation_quadratic_quantum_hamiltonian(scns_hamiltonian)
print("Matriz cambio de base T:")
print(T)
print("Hamiltoniano canónico:")
print(H_n_scns)

Matriz cambio de base T:
[[-1.006 -0.144  0.     0.   ]
 [ 0.112  1.01   0.     0.   ]
 [ 0.     0.    -1.01   0.112]
 [ 0.     0.    -0.144  1.006]]
Hamiltoniano canónico:
[[ 5.774e-01 -1.178e-16 -1.270e-16  2.201e-18]
 [-2.044e-16  5.774e-01  4.409e-17  2.750e-17]
 [-1.270e-16  4.409e-17  5.774e-01 -5.057e-16]
 [ 2.201e-18  2.750e-17 -2.299e-16  5.774e-01]]


In [32]:
v = np.array([[1,2],
              [0,0]])

print(np.sum(v,axis=1))
np.linalg.matrix_rank(v)



[3 0]


1

In [33]:
hamiltonian = np.array([[ 5.963e-01,  1.491e-01, -1.342e-16,  1.573e-17],
                                [ 1.491e-01,  5.963e-01, -6.702e-17,  3.462e-17],
                                [-1.342e-16, -6.702e-17,  5.963e-01, -1.491e-01],
                                [ 1.573e-17,  3.462e-17, -1.491e-01,  5.963e-01]])
        

canonical_hamiltonian, T = canonical_transformation_quadratic_quantum_hamiltonian(hamiltonian)

print(canonical_hamiltonian)
print(T)

[[ 5.774e-01 -3.767e-15 -1.303e-16 -1.523e-17]
 [-3.784e-15  5.774e-01  2.664e-17  3.069e-17]
 [-1.303e-16  2.664e-17  5.774e-01  1.673e-15]
 [-1.523e-17  3.069e-17  1.655e-15  5.774e-01]]
[[ 9.840e-01  2.541e-01  0.000e+00  0.000e+00]
 [ 0.000e+00 -1.016e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  1.016e+00  3.851e-15]
 [ 0.000e+00 -0.000e+00  2.541e-01 -9.840e-01]]


In [34]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
I = np.eye(2)
G = (1 / np.sqrt(2)) * np.block([[-1j * I, 1j * I], [I, I]])
print(G)

[[0.   -0.707j 0.   +0.j    0.   +0.707j 0.   +0.j   ]
 [0.   +0.j    0.   -0.707j 0.   +0.j    0.   +0.707j]
 [0.707+0.j    0.   +0.j    0.707+0.j    0.   +0.j   ]
 [0.   +0.j    0.707+0.j    0.   +0.j    0.707+0.j   ]]


In [36]:
x = np.array([1,2])
y = np.array([3,4])

z = np.array([x]+[y])
print(z)

[[1 2]
 [3 4]]
