In [166]:
from QuantumSCC import *
import numpy as np

In [167]:
C = Capacitor(value = 0.1, unit='nF')
L = Inductor(value = 1, unit = 'nH')

LC = [(0,1,L), (1,2,C),(2,0,C)]

cr = Circuit(LC)

cr.omega_symplectic

cr.diagonal_harmonic_Hamiltonian_expression(precision=3)



----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/ℏ =  4.472 GHz · (a†_1 a_1)
----------------------------------------------------------------------


In [168]:
C = Capacitor(value = 0.1, unit='nF')
L = Inductor(value = 1, unit = 'nH')

LC = [(0,1,L), (0,1,C),(1,2,L),(1,2,C),(2,0,L)]

cr = Circuit(LC)

cr.diagonal_harmonic_Hamiltonian_expression()

----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/ℏ =  3.162 GHz · (a†_1 a_1) +  5.477 GHz · (a†_2 a_2)
----------------------------------------------------------------------


#### LC circuit

In [169]:
# LC circuit


#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 0.1, unit='nF')
L = Inductor(value = 1, unit = 'nH')

LC_oscillator = [(0,1,L), (0,1,C)]

cr = Circuit(LC_oscillator)

cr.diagonal_harmonic_Hamiltonian_expression(precision=3)


----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/ℏ =  3.162 GHz · (a†_1 a_1)
----------------------------------------------------------------------


#### 2 Capacitors and 1 inductor, all in parallel

In [170]:
# 2 C and 1 L all in parallel
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 0.1, unit='nF')
L = Inductor(value = 1, unit = 'nH')

check1 = [(0,1,C),(0,1,C),(0,1,L)]
cr = Circuit(check1)

cr.diagonal_harmonic_Hamiltonian_expression()


----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/ℏ =  2.236 GHz · (a†_1 a_1)
----------------------------------------------------------------------


In [171]:
from scipy.linalg import null_space
M = np.array([[-1,-1,0],[1,1,0]])
K = null_space(M)
print(K)

[[-0.70710678  0.        ]
 [ 0.70710678  0.        ]
 [ 0.          1.        ]]


#### 2 capacitors and 1 inductor all in series

In [172]:
# 2 C and 1 L all in series
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 0.1, unit='nF')
L = Inductor(value = 1, unit = 'nH')

check2 = [(0,1,C),(1,2,C),(2,0,L)]
cr = Circuit(check2)


cr.diagonal_harmonic_Hamiltonian_expression()


----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/ℏ =  4.472 GHz · (a†_1 a_1)
----------------------------------------------------------------------


#### Capacitor coupled oscillators

In [173]:
# COUPLED OSCILLATORS
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 0.1, unit='nF')
C2 = Capacitor(value = 0.1, unit='nF')
Cg = Capacitor(value = 0.2, unit='nF')
L1 = Inductor(value = 1, unit = 'nH')
L2 = Inductor(value = 1, unit = 'nH')

coupled_oscillators = [(0,1,L1), (1,2,Cg), (2,0,L2), (0,1,C1),(2,0,C2)]

cr = Circuit(coupled_oscillators)

cr.diagonal_harmonic_Hamiltonian_expression(precision=3)



----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/ℏ =  1.414 GHz · (a†_1 a_1) +  3.162 GHz · (a†_2 a_2)
----------------------------------------------------------------------


In [174]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        sum = 0
        for k in range(len(Tinv)):
            for l in range(len(Tinv)):
                sum = sum + Tinv[i,k]*Tinv[j,l]*J[k,l]

        conmut[i,j] = sum

print(conmut)

[[ 0.00000000e+00  3.24591973e-17  1.00000000e+00  7.38072101e-17]
 [-3.24591973e-17  0.00000000e+00 -2.88192964e-33  1.00000000e+00]
 [-1.00000000e+00  0.00000000e+00  0.00000000e+00  1.32766375e-16]
 [-7.38072101e-17 -1.00000000e+00 -1.32766375e-16  0.00000000e+00]]


#### Star circuit

In [175]:
#SYMMETRIC STAR CIRCUIT 
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 0.1, unit='nF')
L = Inductor(value = 1, unit = 'nH')

symmetric_starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L), (1,3,L), (2,3,L)]

cr = Circuit(symmetric_starcircuit)

cr.diagonal_harmonic_Hamiltonian_expression()


----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/ℏ =  1.826 GHz · (a†_1 a_1) +  1.826 GHz · (a†_2 a_2)
----------------------------------------------------------------------


In [176]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        sum = 0
        for k in range(len(Tinv)):
            for l in range(len(Tinv)):
                sum = sum + Tinv[i,k]*Tinv[j,l]*J[k,l]

        conmut[i,j] = sum

print(conmut)

[[ 0.00000000e+00  2.42861287e-17  1.00000000e+00 -5.48172618e-16]
 [-2.34187669e-17 -2.71050543e-18 -1.10816656e-16  1.00000000e+00]
 [-1.00000000e+00  1.11022302e-16  1.94798196e-18  0.00000000e+00]
 [ 5.55111512e-16 -1.00000000e+00  2.47362888e-17  0.00000000e+00]]
