In [1]:
from scircuit import *
import numpy as np

In [2]:
#Define the circuit
C = Capacitor(value = 0.5, unit='F')
L1 = Inductor(value = 0.5, unit = 'H')
L2 = Inductor(value = 0.5, unit = 'H')
L3 = Inductor(value = 0.5, unit = 'H')
elements1 = [(0,1,C), (0,1,L1)] 
elements2 = [(0,2,C), (0,1,L1), (1,2,L2)] 
elements3 = [(0,2,C), (0,2,L3), (0,1,L1), (1,2,L2)]
elements4 = [(0,1,C), (0,1,L1), (0,1,L2)] 

cr = Circuit(elements1)

In [3]:
# Calculate omega_2B 
omega_2B = cr.omega_2B
print(f"The matrix expression for omega_2B is:\n{omega_2B}")

# Calculate omega
omega = cr.omega
print(f"The matrix expression for omega is:\n{omega}")
print(f"The determinant of matrix omega is:\n{np.linalg.det(omega)}")

The matrix expression for omega_2B is:
[[ 0.   0.   0.5  0. ]
 [ 0.   0.   0.  -0.5]
 [-0.5  0.   0.   0. ]
 [ 0.   0.5  0.   0. ]]
The matrix expression for omega is:
[[ 0. -1.]
 [ 1.  0.]]
The determinant of matrix omega is:
1.0


In [4]:
np.set_printoptions(precision=3)

# Calculate the Hamiltonian matrix before the variable change
hamiltonian_2B = cr.hamiltonian_2B
print(f"The matrix expression for the H before the variable change is:\n{hamiltonian_2B}")

# Calculate the Hamiltonian matrix after the variable change
hamiltonian = cr.hamiltonian
print(f"The matrix expression for the H after the variable change is:\n{hamiltonian}")

The matrix expression for the H before the variable change is:
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
The matrix expression for the H after the variable change is:
[[1. 0.]
 [0. 1.]]


In [5]:
from scircuit.algebra import *

np.set_printoptions(precision=4, linewidth=100)
N = 6
A = np.random.normal(size=(N, N))
A= np.random.randint(low=-1,high=1, size=(N, N))
A = np.tril(A, k=-1)
A = A - A.T

print("A=\n",A)

J, V = canonical_form(A)

print("J=\n",J)


A=
 [[ 0  1  0  0  0  0]
 [-1  0  1  0  1  1]
 [ 0 -1  0  0  1  1]
 [ 0  0  0  0  1  0]
 [ 0 -1 -1 -1  0  0]
 [ 0 -1 -1  0  0  0]]
J=
 [[ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [-1. -0. -0.  0.  0.  0.]
 [-0. -1. -0.  0.  0.  0.]
 [-0. -0. -1.  0.  0.  0.]]
