In [ ]:
from QuantumSCC import *
import numpy as np


In [2]:
#Define the circuit
C = Capacitor(value = 1, unit='GHz')
L = Inductor(value = 1, unit = 'GHz')
elements1 = [(0,1,C), (0,1,L)] 
elements2 = [(0,1,C), (1,2,L), (2,3,L), (3,0,L)]
elements3 = [(0,1,C), (0,1,L), (1,2,L), (2,3,L), (3,0,L)] 
elements4 = [(0,2,C), (0,1,L), (1,2,L)] 
cr = Circuit(elements4)


In [3]:
# Calculate Kirchhoff matrix (F) 
F = cr.F 

# Calculate kernel matrix (K) using K = [[Floop.T, 0],[0, Fcut.T]]
K = cr.K

# Print kernel matrix
print(f"Kernel matrix using F expression:\n{K}")


Kernel matrix using F expression:
[[-1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1. -1.]]


In [4]:
# Print results of F@K 
print(f"F times kernel matrix using F expression:\n{F@K}")


F times kernel matrix using F expression:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# (dq,dphi) = K (dQ, dPHI) -> (dQ, dPHI) = K^(-1) (dq,dphi)

K_inv = np.linalg.pinv(K)
print(f"The generalized inverse of K is:\n{K_inv}")



The generalized inverse of K is:
[[-3.33333333e-01  3.33333333e-01  3.33333333e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 3.92523115e-17  5.36196546e-17 -1.43673432e-17  6.66666667e-01
   3.33333333e-01  3.33333333e-01]
 [ 7.85046229e-17  1.07239309e-16 -2.87346863e-17  3.33333333e-01
   6.66666667e-01 -3.33333333e-01]]


In [6]:
# Calculate omega_2B 
omega_2B = cr.omega_2B
print(f"The matrix expression for omega_2B is:\n{omega_2B}")

The matrix expression for omega_2B is:
[[ 0.   0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.  -0.5]
 [-0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0. ]]


In [7]:
# Calculate omega_alpha_beta
omega = cr.omega
print(f"The matrix expression for omega_alpha_beta is:\n{omega}")

The matrix expression for omega_alpha_beta is:
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]


In [8]:
np.set_printoptions(precision=3)

# Calculate the Hamiltonian matrix before the variable change
hamiltonian_2B = cr.hamiltonian_2B
print(f"The matrix expression for the H before the variable change is:\n{hamiltonian_2B}")

# Calculate the Hamiltonian matrix after the variable change
hamiltonian = cr.hamiltonian
print(f"The matrix expression for the H after the variable change is:\n{hamiltonian}")


The matrix expression for the H before the variable change is:
[[2.581e+13 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 3.059e+06 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 3.059e+06]]
The matrix expression for the H after the variable change is:
[[ 2.581e+13  0.000e+00  0.000e+00]
 [ 0.000e+00  3.059e+06 -3.059e+06]
 [ 0.000e+00 -3.059e+06  6.118e+06]]
