In [ ]:
from scircuit import *
import numpy as np

#### LC circuit

In [77]:
# LC circuit
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

LC = [(0,1,L), (0,1,C)]

cr = Circuit(LC)

print("Hamiltonian:")
print(cr.linear_canonical_hamiltonian)

print("Basis change matrix, T")
print(cr.T)

print("Hamiltoniano final:")
print(cr.linear_quantum_hamiltonian)

print(cr.V)


vector_JJ:
[]
-----------------------------
Quadratic Hamiltonian:
[[1.63e+02 0.00e+00]
 [0.00e+00 1.55e-01]]
-----------------------------
linear Quadratic Hamiltonian:
[[1.63e+02 0.00e+00]
 [0.00e+00 1.55e-01]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[]
-----------------------------
interaction quadratic Hamiltonian
[[0. 0.]
 [0. 0.]]
-----------------------------
Caso: 1
Hamiltonian:
[[5.03 0.  ]
 [0.   5.03]]
Basis change matrix, T
[[-0.18 -0.  ]
 [ 0.   -5.7 ]]
Hamiltoniano final:
[[ 5.03e+00+0.j -8.88e-16+0.j]
 [-8.88e-16+0.j  5.03e+00+0.j]]
[[1. 0.]
 [0. 1.]]


#### 2 Capacitors and 1 inductor, all in parallel

In [78]:
# 2 C and 1 L all in parallel
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

check1 = [(0,1,C),(0,1,C),(0,1,L)]
cr = Circuit(check1)

print("Hamiltonian:")
print(cr.linear_canonical_hamiltonian)

print("Basis change matrix, T")
print(cr.T)

print("Hamiltoniano final:")
print(cr.linear_quantum_hamiltonian)

print(cr.V)


vector_JJ:
[]
-----------------------------
Quadratic Hamiltonian:
[[1.63e+02+0.j 0.00e+00+0.j]
 [0.00e+00+0.j 7.75e-02+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[1.63e+02+0.j 0.00e+00+0.j]
 [0.00e+00+0.j 7.75e-02+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[]
-----------------------------
interaction quadratic Hamiltonian
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
-----------------------------
Caso: 1
Hamiltonian:
[[3.56+0.j 0.  +0.j]
 [0.  +0.j 3.56+0.j]]
Basis change matrix, T
[[-0.15 -0.  ]
 [ 0.   -6.78]]
Hamiltoniano final:
[[3.56+0.j 0.  +0.j]
 [0.  +0.j 3.56+0.j]]
[[1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 1.+0.j 0.+0.j]]


#### 2 capacitors and 1 inductor all in series

In [79]:
# 2 C and 1 L all in series
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

check2 = [(0,1,C),(1,2,C),(2,0,L)]
cr = Circuit(check2)

print("Hamiltonian:")
print(cr.linear_canonical_hamiltonian)

print("Basis change matrix, T")
print(cr.T)

print("Hamiltoniano final:")
print(cr.linear_quantum_hamiltonian)

print(cr.V)


vector_JJ:
[]
-----------------------------
Quadratic Hamiltonian:
[[ 2.31e+02+0.j -2.64e-15+0.j]
 [-2.64e-15+0.j  2.19e-01+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[ 2.31e+02+0.j -2.64e-15+0.j]
 [-2.64e-15+0.j  2.19e-01+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[]
-----------------------------
interaction quadratic Hamiltonian
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
-----------------------------
Caso: 1
Hamiltonian:
[[ 7.12e+00+0.j -3.87e-16+0.j]
 [-3.87e-16+0.j  7.12e+00+0.j]]
Basis change matrix, T
[[-1.75e-01 -5.55e-17]
 [ 0.00e+00 -5.70e+00]]
Hamiltoniano final:
[[7.12+1.73e-30j 0.  -3.87e-16j]
 [0.  +3.87e-16j 7.12-1.73e-30j]]
[[ 5.95e-01+0.j -1.34e-16+0.j  7.07e-01+0.j]
 [ 5.95e-01+0.j  1.21e-16+0.j -7.07e-01+0.j]
 [ 0.00e+00+0.j -8.41e-01+0.j -1.59e-16+0.j]]


#### Capacitor coupled oscillators

In [80]:
# COUPLED OSCILLATORS
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 1, unit='pF')
C2 = Capacitor(value = 1, unit='pF')
Cg = Capacitor(value = 2, unit='pF')
L1 = Inductor(value = 1, unit = 'nH')
L2 = Inductor(value = 1, unit = 'nH')

coupled_oscillators = [(0,1,L1), (1,2,Cg), (2,0,L2), (0,1,C1),(2,0,C2)]

cr = Circuit(coupled_oscillators)

print("Hamiltonian:")
print(cr.linear_canonical_hamiltonian)

print("Basis change matrix, T")
print(cr.T)

print("Hamiltoniano final:")
print(cr.linear_quantum_hamiltonian)

print(cr.elements)
print(cr.V)


vector_JJ:
[]
-----------------------------
Quadratic Hamiltonian:
[[ 1.01e+02+0.j  6.66e-14+0.j -6.99e-16+0.j  1.39e-15+0.j]
 [ 5.60e-14+0.j  2.64e+02+0.j  4.79e-15+0.j  3.66e-15+0.j]
 [-6.99e-16+0.j  4.79e-15+0.j  6.07e-02+0.j -2.77e-02+0.j]
 [ 1.39e-15+0.j  3.66e-15+0.j -2.77e-02+0.j  9.17e-02+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[ 1.01e+02+0.j  6.66e-14+0.j -6.99e-16+0.j  1.39e-15+0.j]
 [ 5.60e-14+0.j  2.64e+02+0.j  4.79e-15+0.j  3.66e-15+0.j]
 [-6.99e-16+0.j  4.79e-15+0.j  6.07e-02+0.j -2.77e-02+0.j]
 [ 1.39e-15+0.j  3.66e-15+0.j -2.77e-02+0.j  9.17e-02+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[]
-----------------------------
interaction quadratic Hamiltonian
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
-----------------------------
Caso: 1
Hamiltonian:
[[ 2.25e+00+0.j -2.65e-15+0.j  1.73e-16+0.j  5.51e-16+0.j]
 [-2.93e-15+0.j  5.03e+00+0.j -8.5

In [81]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        sum = 0
        for k in range(len(Tinv)):
            for l in range(len(Tinv)):
                sum = sum + Tinv[i,k]*Tinv[j,l]*J[k,l]

        conmut[i,j] = sum

print(conmut)

[[ 4.93e-32  3.46e-16  1.00e+00  1.11e-16]
 [-3.46e-16  0.00e+00  8.33e-17  1.00e+00]
 [-1.00e+00 -8.33e-17  0.00e+00  4.25e-16]
 [-1.11e-16 -1.00e+00 -4.25e-16  0.00e+00]]


#### Star circuit

In [82]:
#SYMMETRIC STAR CIRCUIT 
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

symmetric_starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L), (1,3,L), (2,3,L)]

cr = Circuit(symmetric_starcircuit)

print("Matriz cambio de base T:")
print(cr.T)
print("Hamiltoniano canónico:")
print(cr.linear_canonical_hamiltonian)

print("Hamiltoniano final:")
print(cr.linear_quantum_hamiltonian)



vector_JJ:
[]
-----------------------------
Quadratic Hamiltonian:
[[ 9.75e+01+0.j -2.44e+01+0.j  5.98e-15+0.j -6.39e-15+0.j]
 [-2.44e+01+0.j  9.75e+01+0.j -6.62e-15+0.j  6.39e-15+0.j]
 [ 5.98e-15+0.j -6.62e-15+0.j  9.24e-02+0.j  2.31e-02+0.j]
 [-6.39e-15+0.j  6.39e-15+0.j  2.31e-02+0.j  9.24e-02+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[ 9.75e+01+0.j -2.44e+01+0.j  5.98e-15+0.j -6.39e-15+0.j]
 [-2.44e+01+0.j  9.75e+01+0.j -6.62e-15+0.j  6.39e-15+0.j]
 [ 5.98e-15+0.j -6.62e-15+0.j  9.24e-02+0.j  2.31e-02+0.j]
 [-6.39e-15+0.j  6.39e-15+0.j  2.31e-02+0.j  9.24e-02+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[]
-----------------------------
interaction quadratic Hamiltonian
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
-----------------------------
Caso: 1
Matriz cambio de base T:
[[-1.73e-01  2.83e-03  3.39e-16 -4.45e-02]
 [ 0.00e+00  1.13e-02 -3.73e-16 -1.78e

In [83]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        sum = 0
        for k in range(len(Tinv)):
            for l in range(len(Tinv)):
                sum = sum + Tinv[i,k]*Tinv[j,l]*J[k,l]

        conmut[i,j] = sum

print(conmut)

[[ 1.97e-31  4.26e-17  1.00e+00 -1.38e-16]
 [-5.55e-17  0.00e+00  2.17e-16  1.00e+00]
 [-1.00e+00 -2.17e-16  0.00e+00  2.71e-17]
 [ 1.39e-16 -1.00e+00 -2.71e-17  0.00e+00]]


#### Non-symmetric star circuit

In [84]:
#NON-SYMMETRIC STAR CIRCUIT 
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 1, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
C2 = Capacitor(value = 2, unit='GHz')
L2 = Inductor(value = 2, unit = 'GHz')
C3 = Capacitor(value = 1, unit='GHz')
L3 = Inductor(value = 1, unit = 'GHz')


nonsymmetric_starcircuit = [(0,1,C1), (1,2,C2), (2,0,C3), (0,3,L1), (1,3,L2), (2,3,L3)]

cr = Circuit(nonsymmetric_starcircuit)

print("Matriz cambio de base T:")
print(cr.T)
print("Hamiltoniano canónico:")
print(cr.linear_canonical_hamiltonian)

print("Hamiltoniano final:")
print(cr.linear_quantum_hamiltonian)




vector_JJ:
[]
-----------------------------
Quadratic Hamiltonian:
[[ 1.70e+00+0.j -2.24e-01+0.j  1.15e-16+0.j -1.59e-16+0.j]
 [-2.24e-01+0.j  1.20e+00+0.j  4.66e-17+0.j  1.17e-16+0.j]
 [ 1.15e-16+0.j  4.66e-17+0.j  1.70e+00+0.j  2.24e-01+0.j]
 [-1.59e-16+0.j  1.17e-16+0.j  2.24e-01+0.j  1.20e+00+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[ 1.70e+00+0.j -2.24e-01+0.j  1.15e-16+0.j -1.59e-16+0.j]
 [-2.24e-01+0.j  1.20e+00+0.j  4.66e-17+0.j  1.17e-16+0.j]
 [ 1.15e-16+0.j  4.66e-17+0.j  1.70e+00+0.j  2.24e-01+0.j]
 [-1.59e-16+0.j  1.17e-16+0.j  2.24e-01+0.j  1.20e+00+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[]
-----------------------------
interaction quadratic Hamiltonian
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
-----------------------------
Caso: 1
Matriz cambio de base T:
[[ 7.76e-02  1.00e+00 -2.62e-17  0.00e+00]
 [ 1.00e+00  7.76e-02  0.00e+00  4.64e

In [85]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        sum = 0
        for k in range(len(Tinv)):
            for l in range(len(Tinv)):
                sum = sum + Tinv[i,k]*Tinv[j,l]*J[k,l]

        conmut[i,j] = sum

print(conmut)


[[ 0.00e+00  4.91e-16  1.00e+00  9.71e-17]
 [-4.91e-16  1.16e-33  3.33e-16  1.00e+00]
 [-1.00e+00 -3.33e-16  0.00e+00  3.76e-16]
 [-9.71e-17 -1.00e+00 -3.76e-16  3.24e-32]]


In [86]:
C = Capacitor(value = 1, unit='GHz')
L = Inductor(value = 1, unit = 'GHz')
elements = [(0,1,C), (0,1,L), (1,2,L), (2,3,L), (3,0,L)]

cr = Circuit(elements)

print(cr.F)
print(cr.elements)
print(cr.linear_quantum_hamiltonian)

vector_JJ:
[]
-----------------------------
Quadratic Hamiltonian:
[[1.89+0.j 0.  +0.j]
 [0.  +0.j 2.83+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[1.89+0.j 0.  +0.j]
 [0.  +0.j 2.83+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[]
-----------------------------
interaction quadratic Hamiltonian
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
-----------------------------
Caso: 1
[[-1. -0. -0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0. -1.]]
[[0, 1, <scircuit.elements.Capacitor object at 0x000001D2130E6540>], [1, 2, <scircuit.elements.Inductor object at 0x000001D2130E5610>], [2, 3, <scircuit.elements.Inductor object at 0x000001D2130E5610>], [0, 1, <scircuit.elements.Inductor object at 0x000001D2130E5610>], [3, 0, <scircuit.elements.Inductor object at 0x000001D2130E5610>]]
[[2.31e+00+0.j 2.22e-16+0.j]
 [