In [ ]:
from QuantumSCC import *
import numpy as np

In [2]:
#Define the circuit
C = Capacitor(value = 1, unit='GHz')
Cg = Capacitor(value = 1, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
L2 = Inductor(value = 2, unit = 'GHz')
L3 = Inductor(value = 3, unit = 'GHz')
elements1 = [(0,1,C), (0,1,L1)] 
elements2 = [(0,2,C), (0,1,L1), (1,2,L2)] 
elements3 = [(0,2,C), (0,2,L1), (0,1,L2), (1,2,L3)]
elements4 = [(0,1,C), (0,1,L1), (0,1,L2)] 
elements5 = [(0,3,C), (0,3,L1), (0,1,L2), (1,2,C), (2,3,L1)]
starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L1), (1,3,L1), (2,3,L1)]
starcircuit_4 = [(0,1,C), (1,2,C), (2,3,C), (3,0,C), (0,4,L1), (1,4,L1), (2,4,L1), (3,4,L1)]
starcircuit_nonsymmetric = [(0,1,C), (1,2,C), (2,0,C), (0,3,L2), (1,3,L1), (2,3,L1)]
#coupled_oscillators = [(0,1,C), (0,1,L1), (1,2,Cg), (2,0,C), (2,0,L1)]
coupled_oscillators = [(0,1,L1), (1,2,C), (2,0,L1), (0,1,C), (2,0,C)]

cr = Circuit(coupled_oscillators)


In [3]:
np.set_printoptions(precision=2)
# Calculate omega_2B 
E_2B = cr.omega_2B
print(f"The matrix expression for omega_2B is:\n{E_2B}")

# Calculate omega
E = cr.omega_symplectic
np.set_printoptions(precision=2)
print(f"The matrix expression for omega is:\n{cr.omega_symplectic}")
print(f"The matrix variable change for omega is:\n{np.linalg.inv(cr.V)}")
print(f"The determinant of matrix omega is:\n{np.linalg.det(E)}")


The matrix expression for omega_2B is:
[[ 0.   0.   0.   0.   0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.  -0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5]
 [-0.5  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.  -0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.5  0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.   0.   0.   0. ]]
The matrix expression for omega is:
[[ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [-1. -0.  0.  0.]
 [-0. -1.  0.  0.]]
The matrix variable change for omega is:
[[ 0.00e+00+0.j  1.00e+00+0.j  0.00e+00+0.j -2.21e-17+0.j -2.21e-17+0.j]
 [ 1.19e+00+0.j  0.00e+00+0.j  2.98e-16+0.j  0.00e+00+0.j  0.00e+00+0.j]
 [ 0.00e+00-0.j  0.00e+00-0.j -1.00e+00-0.j  0.00e+00-0.j  0.00e+00-0.j]
 [ 0.00e+00-0.j  1.58e-16+0.j  0.00e+00-0.j -8.41e-01-0.j

In [4]:
np.set_printoptions(precision=2)

# Calculate the Hamiltonian matrix before the variable change
Total_energy_2B = cr.Total_energy_2B
print(f"The matrix expression for the H before the variable change is:\n{Total_energy_2B}")

# Calculate the Hamiltonian matrix in the same basis as E_canonical
Total_energy_symplectic_basis = cr.Total_energy_symplectic_basis
print(f"The matrix expression for the H in the same basis as E_canonical is:\n{Total_energy_symplectic_basis}")

# Calculate the final expression for the Hamiltonian matrix, hamiltonian_xi
hamiltonian = cr.classical_hamiltonian
hamiltonian_prueba = hamiltonian.copy()

print(cr.omega_symplectic)

eigenval,_ = np.linalg.eig(cr.omega_symplectic @ hamiltonian)

print("eig:", eigenval)

print(f"The final matrix expression for the H is:\n{hamiltonian}")



The matrix expression for the H before the variable change is:
[[2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]]
The matrix expression for the H in the same basis as E_canonical is:
[[ 2.00e+00+0.j  1.68e+00+0.j  6.89e-16+0.j -3.34e-16+0.j -7.00e-17+0.j]
 [ 1.68e+00+0.j  2.83e+00+0.j  8.43e-16+0.j  0.00e+00+0.j  5.26e-17+0.j]
 [ 6.89e-16+0.j  8.43e-16+0.j  2.00e+00+0.j -1.19e+00+0.j -1.41e+00+0.j]
 [-3.34e-16+0.j  0.00e+00+0.j -1.19e+00+0.j  2.12e+00+0.j  8.41e-01+0.j]
 [-7.00e-17+0.j  5.26e-17+0.j -1.41e+00+0.j  8.41e-01+0.j  3.00e+00+0.j]]
[[ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [-1. -0.  0.  0.]
 [-0. -1.  0.  0.]]
eig: [-2.22e-16+2.j   -5.20e-18+1.15j -4.25e-16-2.j    4.16e-16-1.15j]
The final matrix expres

In [5]:
np.set_printoptions(precision=3)

print("Canonical Hamiltonian")
print(cr.canonical_hamiltonian)

print("Basis change matrix, T")
print(cr.T)


Canonical Hamiltonian
[[ 1.155e+00+0.j  1.663e-15+0.j  2.517e-17+0.j  1.155e-15+0.j]
 [ 1.663e-15+0.j  2.000e+00+0.j -9.537e-16+0.j  2.117e-15+0.j]
 [ 2.517e-17+0.j -9.488e-16+0.j  1.155e+00+0.j -1.604e-16+0.j]
 [ 1.133e-15+0.j  2.117e-15+0.j -1.604e-16+0.j  2.000e+00+0.j]]
Basis change matrix, T
[[ 0.000e+00  4.044e-16 -1.075e+00  5.617e-16]
 [-1.111e-15 -8.409e-01  6.389e-01 -1.013e-15]
 [ 9.306e-01 -2.429e-16 -1.245e-16 -7.071e-01]
 [-8.879e-16  0.000e+00 -4.329e-16 -1.189e+00]]


In [6]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        conmut[i, j] = J[i,j] * (Tinv[i,i] * Tinv[j,j] - Tinv[i,j] * Tinv[j,i])

print(conmut)

print(cr.T.T @ cr.omega_symplectic @ cr.T)

[[ 0. -0.  1.  0.]
 [-0.  0.  0.  1.]
 [-1. -0.  0.  0.]
 [-0. -1.  0.  0.]]
[[-7.018e-47 -1.123e-15  1.000e+00  7.989e-16]
 [ 1.123e-15 -3.905e-48  1.030e-16  1.000e+00]
 [-1.000e+00 -1.030e-16  2.131e-32 -1.130e-16]
 [-7.989e-16 -1.000e+00  1.130e-16  1.118e-31]]


In [7]:
# Print basis change matrices

print('K basis change matrix')
print(cr.K.T)

print('V basis change matrix')
print(np.linalg.inv(cr.V))

print('T basis change matrix')
print(np.linalg.inv(cr.T))

K basis change matrix
[[ 1.  0. -1.  1. -1.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1. -0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  1.  0.  0.  1.]]
V basis change matrix
[[ 0.000e+00+0.j  1.000e+00+0.j  0.000e+00+0.j -2.211e-17+0.j
  -2.211e-17+0.j]
 [ 1.189e+00+0.j  0.000e+00+0.j  2.982e-16+0.j  0.000e+00+0.j
   0.000e+00+0.j]
 [ 0.000e+00-0.j  0.000e+00-0.j -1.000e+00-0.j  0.000e+00-0.j
   0.000e+00-0.j]
 [ 0.000e+00-0.j  1.576e-16+0.j  0.000e+00-0.j -8.409e-01-0.j
   8.409e-01+0.j]
 [ 0.000e+00+0.j  0.000e+00+0.j  0.000e+00+0.j  7.071e-01+0.j
   7.071e-01+0.j]]
T basis change matrix
[[-5.169e-17 -3.104e-16  1.075e+00 -6.389e-01]
 [-7.071e-01 -1.189e+00 -1.420e-15  1.524e-15]
 [-9.306e-01 -4.476e-16 -9.539e-31 -4.396e-16]
 [ 3.388e-16  3.947e-31 -8.023e-16 -8.409e-01]]


In [8]:
# COUPLED OSCILLATORS
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 1, unit='GHz')
C2 = Capacitor(value = 1, unit='GHz')
Cg = Capacitor(value = 1, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
L2 = Inductor(value = 1, unit = 'GHz')

coupled_oscillators = [(0,1,L1), (1,2,Cg), (2,0,L1), (0,1,C1),(2,0,C1)]

cr = Circuit(coupled_oscillators)

print("Matriz cambio de base T:")
print(cr.T)
print("Hamiltoniano canónico:")
print(cr.canonical_hamiltonian)

Matriz cambio de base T:
[[ 0.000e+00  4.044e-16 -1.075e+00  5.617e-16]
 [-1.111e-15 -8.409e-01  6.389e-01 -1.013e-15]
 [ 9.306e-01 -2.429e-16 -1.245e-16 -7.071e-01]
 [-8.879e-16  0.000e+00 -4.329e-16 -1.189e+00]]
Hamiltoniano canónico:
[[ 1.155e+00+0.j  1.663e-15+0.j  2.517e-17+0.j  1.155e-15+0.j]
 [ 1.663e-15+0.j  2.000e+00+0.j -9.537e-16+0.j  2.117e-15+0.j]
 [ 2.517e-17+0.j -9.488e-16+0.j  1.155e+00+0.j -1.604e-16+0.j]
 [ 1.133e-15+0.j  2.117e-15+0.j -1.604e-16+0.j  2.000e+00+0.j]]


In [9]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        conmut[i, j] = J[i,j] * (Tinv[i,i] * Tinv[j,j] - Tinv[i,j] * Tinv[j,i])

print(conmut)


[[ 0. -0.  1.  0.]
 [-0.  0.  0.  1.]
 [-1. -0.  0.  0.]
 [-0. -1.  0.  0.]]


In [10]:
# COUPLED OSCILLATORS -> Adrian's tests
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 1, unit='GHz')
C2 = Capacitor(value = 1, unit='GHz')
Cg = Capacitor(value = 2, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
L2 = Inductor(value = 1, unit = 'GHz')
Lg = Inductor(value = 2, unit = 'GHz')

coupled_oscillators1 = [(0,1,L1), (1,2,Lg), (2,0,L2), (0,1,C1), (1,2,Cg),(2,0,C2)]
coupled_oscillators2 = [(0,1,L1), (2,0,L2), (0,1,C1), (1,2,Cg), (2,0,C2)]
coupled_oscillators3 = [(0,1,L1), (2,0,L2), (0,1,C1), (2,0,C2)]

cr = Circuit(coupled_oscillators2)

print("Matriz cambio de base T:")
print(cr.T)
print("Hamiltoniano canónico:")
print(cr.canonical_hamiltonian)


# segun adrian tiene que ser 1 y 0.6

Matriz cambio de base T:
[[ 3.475e-16  0.000e+00  7.030e-17 -1.000e+00]
 [ 0.000e+00 -6.827e-17 -1.107e+00 -5.973e-18]
 [-3.097e-17  1.000e+00  4.878e-16 -1.570e-16]
 [ 9.036e-01  3.926e-17 -7.125e-17  7.433e-17]]
Hamiltoniano canónico:
[[ 1.414e+00+0.j -3.541e-17+0.j -1.863e-16+0.j -5.215e-16+0.j]
 [-3.541e-17+0.j  2.000e+00+0.j  6.591e-16+0.j -4.284e-16+0.j]
 [-1.863e-16+0.j  6.591e-16+0.j  1.414e+00+0.j -3.797e-17+0.j]
 [-5.215e-16+0.j -4.284e-16+0.j -3.797e-17+0.j  2.000e+00+0.j]]


In [11]:
# CHECKS CON ADRIAN
np.set_printoptions(linewidth=150, threshold=np.inf)

C = Capacitor(value = 1, unit='GHz')
L = Inductor(value = 1, unit = 'GHz')

# 2 C Y 1 L en paralelo
check1 = [(0,1,C),(0,1,C),(0,1,L)]
cr = Circuit(check1)
hamiltonian = cr.classical_hamiltonian

print("Hamiltoniano canónico:")
print(cr.canonical_hamiltonian)

# 2 C Y 1 L en serie
check2 = [(0,1,C),(1,2,C),(2,0,L)]
cr = Circuit(check2)
hamiltonian = cr.classical_hamiltonian

print("Hamiltoniano canónico:")
print(cr.canonical_hamiltonian)

# 1 C Y 2 L en serie
check3 = [(0,1,C),(1,2,L),(2,0,L)]
cr = Circuit(check3)
hamiltonian = cr.classical_hamiltonian

print("Hamiltoniano canónico:")
print(cr.canonical_hamiltonian)

# 1 C Y 2 L en paralelo
check4 = [(0,1,C),(0,1,L),(0,1,L)]
cr = Circuit(check4)
hamiltonian = cr.classical_hamiltonian

print("Hamiltoniano canónico:")
print(cr.canonical_hamiltonian)

Hamiltoniano canónico:
[[1.414+0.j 0.   +0.j]
 [0.   +0.j 1.414+0.j]]
Hamiltoniano canónico:
[[ 2.828e+00+0.j -3.229e-17+0.j]
 [-3.229e-17+0.j  2.828e+00+0.j]]
Hamiltoniano canónico:
[[1.414+0.j 0.   +0.j]
 [0.   +0.j 1.414+0.j]]
Hamiltoniano canónico:
[[2.828+0.j 0.   +0.j]
 [0.   +0.j 2.828+0.j]]


In [12]:
#SYMMETRIC STAR CIRCUIT 
np.set_printoptions(linewidth=150, threshold=np.inf)

cr = Circuit(starcircuit)
sc_hamiltonian = cr.classical_hamiltonian

print("Matriz cambio de base T:")
print(cr.T)
print("Hamiltoniano canónico:")
print(cr.canonical_hamiltonian)


Matriz cambio de base T:
[[-3.441e-03  1.385e-01  5.429e-01 -8.479e-01]
 [-8.310e-01 -5.539e-01 -1.357e-01  1.305e-01]
 [-5.256e-01  8.420e-01 -2.181e-01 -4.785e-17]
 [ 0.000e+00  8.410e-02 -8.591e-01 -5.363e-01]]
Hamiltoniano canónico:
[[ 1.155e+00+0.j  3.302e-16+0.j  3.589e-16+0.j  2.076e-16+0.j]
 [ 1.723e-16+0.j  1.155e+00+0.j  3.195e-16+0.j -1.658e-17+0.j]
 [ 4.219e-16+0.j  3.127e-16+0.j  1.155e+00+0.j -1.721e-16+0.j]
 [ 1.648e-16+0.j -1.054e-16+0.j -2.077e-16+0.j  1.155e+00+0.j]]


In [13]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        conmut[i, j] = J[i,j] * (Tinv[i,i] * Tinv[j,j] - Tinv[i,j] * Tinv[j,i])

print(conmut)

[[ 0.     0.     0.286  0.   ]
 [ 0.     0.     0.     0.286]
 [-0.286 -0.     0.     0.   ]
 [-0.    -0.286  0.     0.   ]]


In [14]:
#SYMMETRIC SQUARE CIRCUIT 
np.set_printoptions(linewidth=150, threshold=np.inf)

cr = Circuit(starcircuit_4)
sc4_hamiltonian = cr.classical_hamiltonian

print("Matriz cambio de base T:")
print(cr.T)
print("Hamiltoniano canónico:")
print(cr.canonical_hamiltonian)

Matriz cambio de base T:
[[ 8.723e-01 -4.696e-01  2.927e-02 -7.585e-16 -2.248e-02  1.355e-01]
 [-1.153e-01 -5.382e-02  9.840e-01  2.225e-15 -2.909e-01 -7.283e-02]
 [ 5.024e-01  8.278e-01 -2.766e-01 -4.006e-16  1.058e-01 -2.185e-01]
 [ 2.208e-32  3.600e-02 -1.300e-01  8.723e-01 -4.652e-01  7.571e-02]
 [-2.156e-15  2.725e-01  1.566e-01  1.153e-01  2.412e-01  9.508e-01]
 [-5.692e-16  9.825e-20  2.616e-01  5.024e-01  8.630e-01  8.669e-02]]
Hamiltoniano canónico:
[[ 1.000e+00+0.j  5.684e-16+0.j -1.513e-15+0.j -2.885e-16+0.j  4.497e-16+0.j -7.330e-17+0.j]
 [ 9.655e-17+0.j  1.414e+00+0.j  2.500e-16+0.j -4.606e-16+0.j  1.386e-16+0.j -1.095e-16+0.j]
 [-1.287e-15+0.j -7.540e-17+0.j  1.414e+00+0.j  6.308e-16+0.j  2.780e-17+0.j  6.650e-16+0.j]
 [-2.885e-16+0.j -5.198e-16+0.j  6.429e-16+0.j  1.000e+00+0.j  9.382e-16+0.j -1.743e-15+0.j]
 [ 3.705e-16+0.j  2.747e-16+0.j  1.495e-16+0.j  8.343e-16+0.j  1.414e+00+0.j -1.098e-16+0.j]
 [ 1.271e-17+0.j -9.792e-17+0.j  4.973e-16+0.j -1.560e-15+0.j -1.808e-16

In [15]:
# NO-SYMMETRIC STAR CIRCUIT
np.set_printoptions(linewidth=150, threshold=np.inf)


cr = Circuit(starcircuit_nonsymmetric)
scns_hamiltonian = cr.classical_hamiltonian

print("Matriz cambio de base T:")
print(cr.T)
print("Hamiltoniano canónico:")
print(cr.canonical_hamiltonian)

Matriz cambio de base T:
[[-9.407e-01  3.475e-01  1.826e-16 -9.711e-16]
 [-1.372e-01 -9.099e-01  3.482e-18  1.611e-16]
 [ 0.000e+00  4.576e-16 -1.007e+00  1.519e-01]
 [ 1.451e-16  0.000e+00 -3.846e-01 -1.041e+00]]
Hamiltoniano canónico:
[[ 1.155e+00+0.j -3.580e-16+0.j -1.059e-16+0.j  1.009e-15+0.j]
 [-3.672e-16+0.j  1.414e+00+0.j -4.412e-16+0.j -1.258e-16+0.j]
 [-1.059e-16+0.j -4.412e-16+0.j  1.155e+00+0.j -1.612e-16+0.j]
 [ 1.009e-15+0.j -1.258e-16+0.j -1.278e-16+0.j  1.414e+00+0.j]]


In [16]:
from scircuit.algebra import*

c_H = np.array([[ 1.00e+00+0.j,  8.41e-01+0.j,  3.28e-16+0.j, -1.57e-16+0.j],
                                  [ 8.41e-01+0.j,  1.41e+00+0.j,  4.34e-16+0.j, -7.37e-18+0.j],
                                  [ 3.28e-16+0.j,  4.34e-16+0.j,  6.67e-01+0.j, -3.96e-01+0.j],
                                  [-1.57e-16+0.j, -7.37e-18+0.j, -3.96e-01+0.j,  9.43e-01+0.j]])
J = np.zeros((4,4))
I = np.eye(2)
    
J[:2, 2:4] = I
J[2:4, :2] = -I 

K = J @ c_H
eigval_K,eigvec_K = np.linalg.eig(K)
print('eigval K:', eigval_K)
K_N, T = symplectic_transformation(K)

print(T.T @ J @ T)

eigval K: [0.000e+00+0.999j 1.015e-16+0.577j 2.257e-16-0.999j 5.354e-17-0.577j]
[[ 6.155e-35 -4.892e-16  1.000e+00  1.820e-16]
 [ 4.892e-16 -2.460e-35  6.196e-16  1.000e+00]
 [-1.000e+00 -6.196e-16 -5.099e-32 -7.121e-16]
 [-1.820e-16 -1.000e+00  7.121e-16  2.436e-32]]
