In [1]:
from QuantumSCC import *
import numpy as np

## Non-linear tests

#### A- LC oscillator coupled capacitively to a Josephson junction

In [2]:
C_L = Capacitor(value = 1, unit='pF')
C_J = Capacitor(value = 1, unit='pF')
Cg = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C_J)

elements_a = [(0,1,L),(0,1,C_L),(1,2,Cg), (2,0,J)]

cr_a = Circuit(elements_a)


Number of compact flux variables: 1
Number of variables: 4
-----------------------------
vector_JJ:
[[ 0.57735027]
 [-0.20412415]
 [ 0.        ]
 [ 0.        ]]
-----------------------------
total Hamiltonian
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  6.12980180e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.41051737e-01 -4.86998050e-02]
 [ 0.00000000e+00  0.00000000e+00 -4.86998050e-02  2.75487699e-01]]
-----------------------------
compact quadratic hamiltonian
[[0.         0.        ]
 [0.         0.24105174]]
-----------------------------
extended quadratic hamiltonian
[[61.29801803  0.        ]
 [ 0.          0.2754877 ]]
-----------------------------
interaction quadratic hamiltonian
[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.04869981]
 [ 0.          0.         -0.04869981  0.        ]]
--------------------------

#### B- Josephson Junction in series to an inductor and a capacitor

In [3]:
C = Capacitor(value = 1, unit='pF')
C_J = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C_J)

elements_b = [(0,1,J),(1,2,L),(2,0,C)]

cr_b = Circuit(elements_b)



Number of compact flux variables: 1
Number of variables: 4
-----------------------------
vector_JJ:
[[-0.57735027]
 [ 0.25819889]
 [ 0.        ]
 [ 0.        ]]
-----------------------------
total Hamiltonian
[[ 0.          0.          0.          0.        ]
 [ 0.         98.07682884  0.          0.        ]
 [ 0.          0.          0.25826972 -0.11550173]
 [ 0.          0.         -0.11550173  0.51653944]]
-----------------------------
compact quadratic hamiltonian
[[0.         0.        ]
 [0.         0.25826972]]
-----------------------------
extended quadratic hamiltonian
[[98.07682884  0.        ]
 [ 0.          0.51653944]]
-----------------------------
interaction quadratic hamiltonian
[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.11550173]
 [ 0.          0.         -0.11550173  0.        ]]
-----------------------------
Caso: 1


#### C- Josephson junction in parallel to an inductor

In [4]:
C_J = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C_J)

elements_c = [(0,1,J),(0,1,L)]

cr_c = Circuit(elements_c)

Number of compact flux variables: 0
Number of variables: 2
-----------------------------
vector_JJ:
[[1.]
 [0.]]
-----------------------------
total Hamiltonian
[[1.63461381e+02 0.00000000e+00]
 [0.00000000e+00 1.54961831e-01]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[1.63461381e+02 0.00000000e+00]
 [0.00000000e+00 1.54961831e-01]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0.]
 [0. 0.]]
-----------------------------
Caso: 1


#### D- Two Josephson junction in series to an inductor

In [5]:
C_J1 = Capacitor(value = 1, unit='pF')
C_J2 = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J1 = Junction(value = 1, unit = 'GHz', cap = C_J1)
J2 = Junction(value = 1, unit = 'GHz', cap = C_J2)

elements_d = [(0,1,J1),(1,2,J2),(2,0,L)]

cr_d = Circuit(elements_d)

Number of compact flux variables: 1
Number of variables: 4
-----------------------------
vector_JJ:
[[-0.5         0.5       ]
 [ 0.35355339  0.35355339]
 [ 0.          0.        ]
 [ 0.          0.        ]]
-----------------------------
total Hamiltonian
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.17306907e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.09923661e-01 4.53818644e-17]
 [0.00000000e+00 0.00000000e+00 5.89362867e-17 6.19847322e-01]]
-----------------------------
compact quadratic hamiltonian
[[0.         0.        ]
 [0.         0.30992366]]
-----------------------------
extended quadratic hamiltonian
[[81.7306907   0.        ]
 [ 0.          0.61984732]]
-----------------------------
interaction quadratic hamiltonian
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.53818644e-17]
 [0.000000

## Some tests and other things

In [6]:
# COUPLED OSCILLATORS
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 1, unit='pF')
C2 = Capacitor(value = 1, unit='pF')
Cg = Capacitor(value = 2, unit='pF')
L1 = Inductor(value = 1, unit = 'nH')
L2 = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C1)

coupled_oscillators = [(0,1,J), (1,2,Cg), (2,0,L2),(2,0,C2)]
coupled_oscillators = [(0,1,J), (1,2,Cg), (2,3,L2),(2,3,C2), (3,0,Cg)]
#coupled_oscillators = [(0,1,J), (1,2,Cg), (2,0,J)]
#coupled_oscillators = [(0,1,J), (1,2,Cg), (2,3,L2),(2,3,C2),(3,4,Cg),(4,0,J)]
#coupled_oscillators = [(0,1,L), (0,1,C), (1,2,Cg), (2,3,L2),(2,3,C2),(3,4,Cg),(4,0,L),(4,0,C)]

cr = Circuit(coupled_oscillators)




Number of compact flux variables: 1
Number of variables: 4
-----------------------------
vector_JJ:
[[1.]
 [0.]
 [0.]
 [0.]]
-----------------------------
total Hamiltonian
[[ 0.          0.          0.          0.        ]
 [ 0.         68.10890892  0.          0.        ]
 [ 0.          0.          0.10330789 -0.08002195]
 [ 0.          0.         -0.08002195  0.24793893]]
-----------------------------
compact quadratic hamiltonian
[[0.         0.        ]
 [0.         0.10330789]]
-----------------------------
extended quadratic hamiltonian
[[68.10890892  0.        ]
 [ 0.          0.24793893]]
-----------------------------
interaction quadratic hamiltonian
[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.08002195]
 [ 0.          0.         -0.08002195  0.        ]]
-----------------------------
Caso: 1


In [7]:
C = Capacitor(value = 1, unit='pF')
Cg = Capacitor(value = 2, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C1)

coupled_oscillators1 = [(0,1,L), (0,1,C), (1,2,Cg), (2,3,L2),(2,3,C2),(3,4,Cg),(4,0,L),(4,0,C)]
cr1 = Circuit(coupled_oscillators1)


Number of compact flux variables: 0
Number of variables: 6
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[ 8.17306907e+01 -8.91712652e-16  4.33022508e-16  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.44871271e+01  1.45622973e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.45622973e+01  7.39468154e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.09923661e-01 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.55111512e-17  1.74332059e-01  7.24767598e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00  7.24767598e-02  2.71183204e-01]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[ 8.17306907e+01 -8.91712652e-16  4.33022508e-16  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.44871271e+

In [8]:
coupled_oscillators2 = [(0,1,J), (1,2,Cg), (2,3,L2),(2,3,C2),(3,4,Cg),(4,5,J), (5,0,Cg)]

#coupled_oscillators2 = [(0,1,J), (1,2,Cg), (2,3,L2),(2,3,C2),(3,4,Cg),(4,5,L2),(4,5,C2), (5,6,Cg), (6,7,L2), (6,7,C2),(7,0,Cg)]

cr2 = Circuit(coupled_oscillators2)

Number of compact flux variables: 2
Number of variables: 6
-----------------------------
vector_JJ:
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
-----------------------------
total Hamiltonian
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.26495028e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.20525868e-01 -3.44359624e-02 -5.16539435e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.44359624e-02  1.20525868e-01 -5.16539435e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.16539435e-02 -5.16539435e-02  2.71183204e-01]]
-----------------------------
compact quadratic hamiltonian
[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.12052587 -0

In [9]:
C = Capacitor(value = 1, unit='GHz')
L = Inductor(value = 1, unit = 'GHz')
elements = [(0,2,C), (0,1,L), (1,2,L)] 

cr = Circuit(elements)



Number of compact flux variables: 0
Number of variables: 2
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[1. 0.]
 [0. 2.]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[1. 0.]
 [0. 2.]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0.]
 [0. 0.]]
-----------------------------
Caso: 1
