In [1]:
from scircuit import *
import numpy as np

In [2]:
#Define the circuit
C = Capacitor(value = 0.5, unit='F')
L1 = Inductor(value = 0.5, unit = 'H')
L2 = Inductor(value = 0.5, unit = 'H')
L3 = Inductor(value = 0.5, unit = 'H')
elements1 = [(0,1,C), (0,1,L1)] 
elements2 = [(0,2,C), (0,1,L1), (1,2,L2)] 
elements3 = [(0,2,C), (0,2,L3), (0,1,L1), (1,2,L2)]
elements4 = [(0,1,C), (0,1,L1), (0,1,L2)] 
starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L1), (1,3,L1), (2,3,L1)]

cr = Circuit(starcircuit)

In [3]:
# Calculate omega_2B 
E_2B = cr.E_2B
print(f"The matrix expression for omega_2B is:\n{E_2B}")

# Calculate omega
E = cr.E_canonical
print(f"The matrix expression for omega is:\n{cr.E_canonical}")
print(f"The matrix variable change for omega is:\n{cr.canonical_basis_change}")
print(f"The determinant of matrix omega is:\n{np.linalg.det(E)}")

The matrix expression for omega_2B is:
[[ 0.   0.   0.   0.   0.   0.   0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.  -0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5]
 [-0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.5  0.   0.   0.   0.   0.   0. ]]
The matrix expression for omega is:
[[ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [-1. -0.  0.  0.  0.  0.]
 [-0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
The m

In [4]:
np.set_printoptions(precision=3)

# Calculate the Hamiltonian matrix before the variable change
hamiltonian_2B = cr.hamiltonian_2B
print(f"The matrix expression for the H before the variable change is:\n{hamiltonian_2B}")

# Calculate the Hamiltonian matrix in the same basis as E_canonical
hamiltonian = cr.hamiltonian
print(f"The matrix expression for the H in the same basis as E_canonical is:\n{hamiltonian}")

# Calculate the final expression for the Hamiltonian matrix, hamiltonian_xi
hamiltonian_xi = cr.hamiltonian_xi
print(f"The final matrix expression for the His:\n{hamiltonian_xi}")



The matrix expression for the H before the variable change is:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
The matrix expression for the H in the same basis as E_canonical is:
[[ 1.618e+00 -4.174e-17  3.897e-16  4.419e-16 -5.229e-16 -1.751e+00]
 [-4.174e-17  6.180e-01 -5.135e-16  1.486e-17 -2.554e-01  3.297e-17]
 [ 3.897e-16 -4.261e-16  1.618e+00 -1.391e-16 -1.751e+00  8.497e-17]
 [ 1.850e-16  1.486e-17 -1.391e-16  6.180e-01  1.991e-16 -2.554e-01]
 [-5.229e-16 -2.554e-01 -1.751e+00  1.991e-16  3.000e+00  0.000e+00]
 [-1.751e+00  3.297e-17  8.497e-17 -2.554e-01  0.000e+