In [80]:
from QuantumSCC import *
import numpy as np

In [81]:
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

LC = [(0,1,L), (1,2,C),(2,0,C)]

cr = Circuit(LC)

cr.omega_symplectic

cr.circuit_description()


Number of compact flux variables: 0
Number of variables: 2
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[108.97425427   0.        ]
 [  0.           0.46488549]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[108.97425427   0.        ]
 [  0.           0.46488549]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0.]
 [0. 0.]]
-----------------------------
Caso: 1
----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/h (GHz) =  7.118 (a†_0 a_0 + 1/2)
----------------------------------------------------------------------


In [82]:
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

LC = [(0,1,L), (0,1,C),(1,2,L),(1,2,C),(2,0,L)]

cr = Circuit(LC)

cr.circuit_description()

Number of compact flux variables: 0
Number of variables: 4
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[ 3.26922763e+02  1.63461381e+02  0.00000000e+00  0.00000000e+00]
 [ 1.63461381e+02  3.26922763e+02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.54961831e-01 -1.20415416e-18]
 [ 0.00000000e+00  0.00000000e+00 -2.86736987e-18  1.54961831e-01]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[ 3.26922763e+02  1.63461381e+02  0.00000000e+00  0.00000000e+00]
 [ 1.63461381e+02  3.26922763e+02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.54961831e-01 -1.20415416e-18]
 [ 0.00000000e+00  0.00000000e+00 -2.86736987e-18  1.54961831e-01]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------
Caso: 1
------------------------

#### LC circuit

In [83]:
# LC circuit
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

LC = [(0,1,L), (0,1,C)]

cr = Circuit(LC)

cr.circuit_description()


Number of compact flux variables: 0
Number of variables: 2
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[1.63461381e+02 0.00000000e+00]
 [0.00000000e+00 1.54961831e-01]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[1.63461381e+02 0.00000000e+00]
 [0.00000000e+00 1.54961831e-01]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0.]
 [0. 0.]]
-----------------------------
Caso: 1
----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/h (GHz) =  5.033 (a†_0 a_0 + 1/2)
----------------------------------------------------------------------


#### 2 Capacitors and 1 inductor, all in parallel

In [84]:
# 2 C and 1 L all in parallel
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

check1 = [(0,1,C),(0,1,C),(0,1,L)]
cr = Circuit(check1)

cr.circuit_description()


Number of compact flux variables: 0
Number of variables: 2
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[1.63461381e+02 0.00000000e+00]
 [0.00000000e+00 7.74809153e-02]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[1.63461381e+02 0.00000000e+00]
 [0.00000000e+00 7.74809153e-02]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0.]
 [0. 0.]]
-----------------------------
Caso: 1
----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/h (GHz) =  3.559 (a†_0 a_0 + 1/2)
----------------------------------------------------------------------


In [85]:
from scipy.linalg import null_space
M = np.array([[-1,-1,0],[1,1,0]])
K = null_space(M)
print(K)

[[-0.70710678  0.        ]
 [ 0.70710678  0.        ]
 [ 0.          1.        ]]


#### 2 capacitors and 1 inductor all in series

In [86]:
# 2 C and 1 L all in series
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

check2 = [(0,1,C),(1,2,C),(2,0,L)]
cr = Circuit(check2)


cr.circuit_description()


Number of compact flux variables: 0
Number of variables: 2
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[108.97425427   0.        ]
 [  0.           0.46488549]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[108.97425427   0.        ]
 [  0.           0.46488549]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0.]
 [0. 0.]]
-----------------------------
Caso: 1
----------------------------------------------------------------------
Diagonalized quantum Hamiltonian:
H/h (GHz) =  7.118 (a†_0 a_0 + 1/2)
----------------------------------------------------------------------


#### Capacitor coupled oscillators

In [87]:
# COUPLED OSCILLATORS
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 3, unit='pF')
C2 = Capacitor(value = 1, unit='pF')
Cg = Capacitor(value = 2, unit='pF')
L1 = Inductor(value = 1, unit = 'nH')
L2 = Inductor(value = 1, unit = 'nH')

coupled_oscillators = [(0,1,L1), (1,2,Cg), (2,0,L2), (0,1,C1),(2,0,C2)]

cr = Circuit(coupled_oscillators)

cr.circuit_description()



Number of compact flux variables: 0
Number of variables: 4
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[ 3.26922763e+02  1.63461381e+02  0.00000000e+00  0.00000000e+00]
 [ 1.63461381e+02  1.63461381e+02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  4.22623174e-02 -1.40874391e-02]
 [ 0.00000000e+00  0.00000000e+00 -1.40874391e-02  5.63497566e-02]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[ 3.26922763e+02  1.63461381e+02  0.00000000e+00  0.00000000e+00]
 [ 1.63461381e+02  1.63461381e+02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  4.22623174e-02 -1.40874391e-02]
 [ 0.00000000e+00  0.00000000e+00 -1.40874391e-02  5.63497566e-02]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------
Caso: 1
------------------------

In [88]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        sum = 0
        for k in range(len(Tinv)):
            for l in range(len(Tinv)):
                sum = sum + Tinv[i,k]*Tinv[j,l]*J[k,l]

        conmut[i,j] = sum

print(conmut)

[[ 0.00000000e+00  7.95959626e-17  1.00000000e+00  4.16333634e-16]
 [-7.95959626e-17 -3.08148791e-33 -1.11022302e-16  1.00000000e+00]
 [-1.00000000e+00  1.11022302e-16  0.00000000e+00  3.67729421e-16]
 [-4.16333634e-16 -1.00000000e+00 -3.67729421e-16  0.00000000e+00]]


#### Star circuit

In [89]:
#SYMMETRIC STAR CIRCUIT 
np.set_printoptions(linewidth=150, threshold=np.inf)

#C = Capacitor(value = 1, unit='GHz')
#L = Inductor(value = 1, unit = 'GHz')
C = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')

symmetric_starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L), (1,3,L), (2,3,L)]

cr = Circuit(symmetric_starcircuit)

cr.circuit_description()


Number of compact flux variables: 0
Number of variables: 4
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[ 1.08974254e+02  5.44871271e+01  0.00000000e+00  0.00000000e+00]
 [ 5.44871271e+01  1.08974254e+02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.03307887e-01 -5.16539435e-02]
 [ 0.00000000e+00  0.00000000e+00 -5.16539435e-02  1.03307887e-01]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[ 1.08974254e+02  5.44871271e+01  0.00000000e+00  0.00000000e+00]
 [ 5.44871271e+01  1.08974254e+02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.03307887e-01 -5.16539435e-02]
 [ 0.00000000e+00  0.00000000e+00 -5.16539435e-02  1.03307887e-01]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------
Caso: 1
------------------------

In [90]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        sum = 0
        for k in range(len(Tinv)):
            for l in range(len(Tinv)):
                sum = sum + Tinv[i,k]*Tinv[j,l]*J[k,l]

        conmut[i,j] = sum

print(conmut)

[[ 0.00000000e+00 -4.36933476e-17  1.00000000e+00  1.79977561e-16]
 [ 0.00000000e+00  0.00000000e+00 -6.78710560e-17  1.00000000e+00]
 [-1.00000000e+00  6.77626358e-17  0.00000000e+00 -5.31259065e-18]
 [-1.66533454e-16 -1.00000000e+00  5.31259065e-18  0.00000000e+00]]


#### Non-symmetric star circuit

In [91]:
#NON-SYMMETRIC STAR CIRCUIT 
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 1, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
C2 = Capacitor(value = 2, unit='GHz')
L2 = Inductor(value = 2, unit = 'GHz')
C3 = Capacitor(value = 1, unit='GHz')
L3 = Inductor(value = 1, unit = 'GHz')


nonsymmetric_starcircuit = [(0,1,C1), (1,2,C2), (2,0,C3), (0,3,L1), (1,3,L2), (2,3,L3)]

cr = Circuit(nonsymmetric_starcircuit)





Number of compact flux variables: 0
Number of variables: 4
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[ 1.5  0.5  0.   0. ]
 [ 0.5  1.5  0.   0. ]
 [ 0.   0.   1.5 -1. ]
 [ 0.   0.  -1.   2. ]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[ 1.5  0.5  0.   0. ]
 [ 0.5  1.5  0.   0. ]
 [ 0.   0.   1.5 -1. ]
 [ 0.   0.  -1.   2. ]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------
Caso: 1


In [92]:
Tinv = np.linalg.inv(cr.T)
J = cr.omega_symplectic
conmut = np.zeros((len(Tinv), len(Tinv)))

for i in range(len(Tinv)):
    for j in range(len(Tinv)):
        sum = 0
        for k in range(len(Tinv)):
            for l in range(len(Tinv)):
                sum = sum + Tinv[i,k]*Tinv[j,l]*J[k,l]

        conmut[i,j] = sum

print(conmut)


[[ 0.00000000e+00  3.55564827e-16  1.00000000e+00 -5.55111512e-16]
 [-3.55564827e-16  0.00000000e+00 -2.77555756e-16  1.00000000e+00]
 [-1.00000000e+00  2.77555756e-16  0.00000000e+00  3.51273349e-16]
 [ 5.55111512e-16 -1.00000000e+00 -3.51273349e-16  1.23259516e-32]]


In [93]:
C = Capacitor(value = 1, unit='GHz')
L = Inductor(value = 1, unit = 'GHz')
elements = [(0,1,C), (0,1,L), (1,2,L), (2,3,L), (3,0,L)]

cr = Circuit(elements)


Number of compact flux variables: 0
Number of variables: 2
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[[2.66666667 0.        ]
 [0.         2.        ]]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[[2.66666667 0.        ]
 [0.         2.        ]]
-----------------------------
interaction quadratic hamiltonian
[[0. 0.]
 [0. 0.]]
-----------------------------
Caso: 1


In [94]:
elementsC = [(0,1,C),(0,1,C)]
cr = Circuit(elementsC)


Number of compact flux variables: 0
Number of variables: 0
-----------------------------
vector_JJ:
[]
-----------------------------
total Hamiltonian
[]
-----------------------------
compact quadratic hamiltonian
[]
-----------------------------
extended quadratic hamiltonian
[]
-----------------------------
interaction quadratic hamiltonian
[]
-----------------------------
Caso: 1
