In [1]:
from QuantumSCC import *
import numpy as np

## Non-linear tests

#### An LC oscillator coupled capacitively to a Josephson junction

In [2]:
C_L = Capacitor(value = 1, unit='pF')
C_J = Capacitor(value = 1, unit='pF')
Cg = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C_J)

elements_a = [(0,1,L),(0,1,C_L),(1,2,Cg), (2,0,J)]

cr_a = Circuit(elements_a)

vector_JJ:
[[-6.56e-32+0.j]
 [ 8.41e-01+0.j]
 [ 2.51e-16+0.j]
 [ 0.00e+00+0.j]]
-----------------------------
Quadratic Hamiltonian:
[[ 1.63e+02+0.j  0.00e+00+0.j  3.54e-14+0.j -4.70e-15+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j]
 [ 3.54e-14+0.j  0.00e+00+0.j  1.03e-01+0.j -6.14e-02+0.j]
 [-4.70e-15+0.j  0.00e+00+0.j -6.14e-02+0.j  1.46e-01+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[1.63e+02+0.j 3.54e-14+0.j]
 [3.54e-14+0.j 1.03e-01+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[[0.  +0.j 0.  +0.j]
 [0.  +0.j 0.15+0.j]]
-----------------------------
interaction quadratic Hamiltonian
[[ 0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j -4.70e-15+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j -6.14e-02+0.j]
 [-4.70e-15+0.j  0.00e+00+0.j -6.14e-02+0.j  0.00e+00+0.j]]
-----------------------------
Caso: 1


In [3]:
print("Hamiltonian:")
print(cr_a.linear_canonical_hamiltonian)

print("Basis change matrix, T")
print(cr_a.T)

print("Hamiltoniano final:")
print(cr_a.linear_quantum_hamiltonian)

print(cr_a.nonlinear_quadratic_hamiltonian)

print(cr_a.V)

Hamiltonian:
[[ 4.11e+00+0.j -9.83e-16+0.j]
 [-9.83e-16+0.j  4.11e+00+0.j]]
Basis change matrix, T
[[-1.59e-01  1.40e-15]
 [ 0.00e+00 -6.31e+00]]
Hamiltoniano final:
[[ 4.11e+00-4.93e-31j -4.44e-16-9.83e-16j]
 [-4.44e-16+9.83e-16j  4.11e+00+4.93e-31j]]
[[0.  +0.j 0.  +0.j]
 [0.  +0.j 0.15+0.j]]
[[-6.56e-32+0.j  8.41e-01+0.j  2.51e-16+0.j  0.00e+00+0.j -5.81e-49+0.j]
 [ 1.00e+00+0.j  0.00e+00+0.j  1.68e-16+0.j  0.00e+00+0.j  1.02e-16+0.j]
 [ 1.45e-17+0.j  0.00e+00+0.j  1.08e-17+0.j  5.95e-01+0.j  7.07e-01+0.j]
 [ 1.53e-16+0.j  0.00e+00+0.j  5.91e-17+0.j -5.95e-01+0.j  7.07e-01+0.j]
 [-6.16e-33+0.j  0.00e+00+0.j  1.00e+00+0.j  0.00e+00+0.j -2.40e-17+0.j]]


#### A Josephson Junction in parallel to an inductor and a capacitor

In [4]:
C = Capacitor(value = 1, unit='pF')
C_J = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C_J)

elements_b = [(0,1,J),(1,2,L),(2,0,C)]

cr_b = Circuit(elements_b)

vector_JJ:
[[1.]
 [0.]
 [0.]
 [0.]]
-----------------------------
Quadratic Hamiltonian:
[[ 1.63e+02 -1.63e+02  0.00e+00  0.00e+00]
 [-1.63e+02  1.63e+02  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  1.55e-01  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  1.55e-01]]
-----------------------------
linear Quadratic Hamiltonian:
[[1.63e+02 0.00e+00]
 [0.00e+00 1.55e-01]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[[1.63e+02 0.00e+00]
 [0.00e+00 1.55e-01]]
-----------------------------
interaction quadratic Hamiltonian
[[   0.   -163.46    0.      0.  ]
 [-163.46    0.      0.      0.  ]
 [   0.      0.      0.      0.  ]
 [   0.      0.      0.      0.  ]]
-----------------------------
Caso: 2


#### A Josephson junction in parallel to an inductor

In [5]:
C_J = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C_J)

elements_c = [(0,1,J),(0,1,L)]

cr_c = Circuit(elements_c)

vector_JJ:
[[1.+0.j]
 [0.+0.j]]
-----------------------------
Quadratic Hamiltonian:
[[1.63e+02+0.j 0.00e+00+0.j]
 [0.00e+00+0.j 1.55e-01+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[]
-----------------------------
nonlinear Quadratic Hamiltonian:
[[1.63e+02+0.j 0.00e+00+0.j]
 [0.00e+00+0.j 1.55e-01+0.j]]
-----------------------------
interaction quadratic Hamiltonian
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
-----------------------------
Caso: 2


#### Two Josephson junction in series to an inductor

In [6]:
C_J1 = Capacitor(value = 1, unit='pF')
C_J2 = Capacitor(value = 1, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J1 = Junction(value = 1, unit = 'GHz', cap = C_J1)
J2 = Junction(value = 1, unit = 'GHz', cap = C_J2)

elements_d = [(0,1,J1),(1,2,J2),(2,0,L)]

cr_d = Circuit(elements_d)

vector_JJ:
[[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]
 [ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]
-----------------------------
Quadratic Hamiltonian:
[[ 1.63e+02+0.j -1.63e+02+0.j  0.00e+00+0.j  0.00e+00+0.j]
 [-1.63e+02+0.j  1.63e+02+0.j  0.00e+00+0.j  0.00e+00+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j  1.55e-01+0.j  0.00e+00+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j  1.55e-01+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[]
-----------------------------
nonlinear Quadratic Hamiltonian:
[[ 1.63e+02+0.j -1.63e+02+0.j  0.00e+00+0.j  0.00e+00+0.j]
 [-1.63e+02+0.j  1.63e+02+0.j  0.00e+00+0.j  0.00e+00+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j  1.55e-01+0.j  0.00e+00+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j  1.55e-01+0.j]]
-----------------------------
interaction quadratic Hamiltonian
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
-----------------------------
Caso: 2


## Some tests and other things

In [7]:
# COUPLED OSCILLATORS
np.set_printoptions(linewidth=150, threshold=np.inf)

C1 = Capacitor(value = 1, unit='pF')
C2 = Capacitor(value = 1, unit='pF')
Cg = Capacitor(value = 2, unit='pF')
L1 = Inductor(value = 1, unit = 'nH')
L2 = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C1)

coupled_oscillators = [(0,1,J), (1,2,Cg), (2,0,L2),(2,0,C2)]
coupled_oscillators = [(0,1,J), (1,2,Cg), (2,3,L2),(2,3,C2), (3,0,Cg)]
#coupled_oscillators = [(0,1,J), (1,2,Cg), (2,0,J)]
#coupled_oscillators = [(0,1,J), (1,2,Cg), (2,3,L2),(2,3,C2),(3,4,Cg),(4,0,J)]
#coupled_oscillators = [(0,1,L), (0,1,C), (1,2,Cg), (2,3,L2),(2,3,C2),(3,4,Cg),(4,0,L),(4,0,C)]

cr = Circuit(coupled_oscillators)


print("Hamiltonian:")
print(cr.linear_canonical_hamiltonian)

print("Basis change matrix, T")
print(cr.T)

print("Hamiltoniano final:")
print(cr.linear_quantum_hamiltonian)

print(cr.nonlinear_quadratic_hamiltonian)

print(cr.V)



vector_JJ:
[[-2.51e-16+0.j]
 [ 8.41e-01+0.j]
 [ 0.00e+00+0.j]
 [ 0.00e+00+0.j]]
-----------------------------
Quadratic Hamiltonian:
[[ 1.63e+02+0.j  0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j  0.00e+00+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j  1.03e-01+0.j -6.14e-02+0.j]
 [ 0.00e+00+0.j  0.00e+00+0.j -6.14e-02+0.j  1.46e-01+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[1.63e+02+0.j 0.00e+00+0.j]
 [0.00e+00+0.j 1.03e-01+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[[0.  +0.j 0.  +0.j]
 [0.  +0.j 0.15+0.j]]
-----------------------------
interaction quadratic Hamiltonian
[[ 0.  +0.j  0.  +0.j  0.  +0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  0.  +0.j  0.  +0.j]
 [ 0.  +0.j  0.  +0.j  0.  +0.j -0.06+0.j]
 [ 0.  +0.j  0.  +0.j -0.06+0.j  0.  +0.j]]
-----------------------------
Caso: 1
Hamiltonian:
[[4.11+0.j 0.  +0.j]
 [0.  +0.j 4.11+0.j]]
Basis change matrix, T
[[-0.16 -0.  ]
 [ 0.   -6.31]]
Hamiltoniano final:


In [8]:
C = Capacitor(value = 1, unit='pF')
Cg = Capacitor(value = 2, unit='pF')
L = Inductor(value = 1, unit = 'nH')
J = Junction(value = 1, unit = 'GHz', cap = C1)

coupled_oscillators1 = [(0,1,L), (0,1,C), (1,2,Cg), (2,3,L2),(2,3,C2),(3,4,Cg),(4,0,L),(4,0,C)]
cr1 = Circuit(coupled_oscillators1)


vector_JJ:
[]
-----------------------------
Quadratic Hamiltonian:
[[ 1.08e+02+0.j  1.58e-14+0.j -4.02e-14+0.j -8.06e-16+0.j  2.10e-14+0.j  3.69e-15+0.j]
 [ 8.39e-15+0.j  1.63e+02+0.j  8.38e-14+0.j  1.72e-14+0.j  3.06e-14+0.j  2.73e-15+0.j]
 [-4.88e-14+0.j  6.15e-14+0.j  3.49e+02+0.j  6.21e-14+0.j -2.64e-14+0.j  1.02e-14+0.j]
 [-8.06e-16+0.j  1.72e-14+0.j  6.21e-14+0.j  6.82e-02+0.j  8.01e-17+0.j -2.23e-02+0.j]
 [ 2.10e-14+0.j  3.06e-14+0.j -2.64e-14+0.j  7.51e-17+0.j  1.55e-01+0.j -2.05e-18+0.j]
 [ 3.69e-15+0.j  2.73e-15+0.j  1.02e-14+0.j -2.23e-02+0.j  2.89e-18+0.j  6.95e-02+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[ 1.08e+02+0.j  1.58e-14+0.j -4.02e-14+0.j -8.06e-16+0.j  2.10e-14+0.j  3.69e-15+0.j]
 [ 8.39e-15+0.j  1.63e+02+0.j  8.38e-14+0.j  1.72e-14+0.j  3.06e-14+0.j  2.73e-15+0.j]
 [-4.88e-14+0.j  6.15e-14+0.j  3.49e+02+0.j  6.21e-14+0.j -2.64e-14+0.j  1.02e-14+0.j]
 [-8.06e-16+0.j  1.72e-14+0.j  6.21e-14+0.j  6.82e-02+0.j  8.01e-17+0.j -2.23e-02+0.j]
 [

In [9]:
coupled_oscillators2 = [(0,1,J), (1,2,Cg), (2,3,L2),(2,3,C2),(3,4,Cg),(4,5,J), (5,0,Cg)]

cr2 = Circuit(coupled_oscillators2)

vector_JJ:
[[ 7.07e-01+0.j -7.07e-01+0.j]
 [-8.79e-17+0.j  3.08e-16+0.j]
 [ 5.37e-01+0.j  5.37e-01+0.j]
 [ 8.99e-18+0.j  8.09e-34+0.j]
 [-2.75e-18+0.j  8.24e-18+0.j]
 [ 6.35e-18+0.j  6.37e-18+0.j]]
-----------------------------
Quadratic Hamiltonian:
[[ 5.74e-34+0.j  8.20e-35+0.j  2.51e-35+0.j  7.60e-18+0.j  2.35e-18+0.j -5.48e-18+0.j]
 [ 8.20e-35+0.j  1.63e+02+0.j  7.36e-36+0.j  1.51e-18+0.j  9.46e-20+0.j -2.20e-19+0.j]
 [ 2.51e-35+0.j  7.36e-36+0.j  5.47e-36+0.j  8.20e-19+0.j -1.77e-19+0.j  4.11e-19+0.j]
 [ 7.60e-18+0.j  1.51e-18+0.j  8.20e-19+0.j  1.55e-01+0.j -4.41e-19+0.j -6.41e-18+0.j]
 [ 2.35e-18+0.j  9.46e-20+0.j -1.77e-19+0.j  1.34e-18+0.j  1.21e-01+0.j -6.41e-02+0.j]
 [-5.48e-18+0.j -2.20e-19+0.j  4.11e-19+0.j -8.97e-18+0.j -6.41e-02+0.j  1.49e-01+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[1.63e+02+0.j 9.46e-20+0.j]
 [9.46e-20+0.j 1.21e-01+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[[ 5.74e-34+0.j  2.51e-35+0.j  7.60e-18+0.j 

In [10]:
C = Capacitor(value = 1, unit='GHz')
L = Inductor(value = 1, unit = 'GHz')
elements = [(0,2,C), (0,1,L), (1,2,L)] 

cr = Circuit(elements)

print(cr.linear_quadratic_hamiltonian)

vector_JJ:
[]
-----------------------------
Quadratic Hamiltonian:
[[1.+0.j 0.+0.j]
 [0.+0.j 2.+0.j]]
-----------------------------
linear Quadratic Hamiltonian:
[[1.+0.j 0.+0.j]
 [0.+0.j 2.+0.j]]
-----------------------------
nonlinear Quadratic Hamiltonian:
[]
-----------------------------
interaction quadratic Hamiltonian
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
-----------------------------
Caso: 1
[[1.+0.j 0.+0.j]
 [0.+0.j 2.+0.j]]
