In [1]:
from scircuit import *
import numpy as np

In [2]:
#Define the circuit
C = Capacitor(value = 1, unit='GHz')
Cg = Capacitor(value = 1, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
L2 = Inductor(value = 2, unit = 'GHz')
L3 = Inductor(value = 3, unit = 'GHz')
elements1 = [(0,1,C), (0,1,L1)] 
elements2 = [(0,2,C), (0,1,L1), (1,2,L2)] 
elements3 = [(0,2,C), (0,2,L1), (0,1,L2), (1,2,L3)]
elements4 = [(0,1,C), (0,1,L1), (0,1,L2)] 
elements5 = [(0,3,C), (0,3,L1), (0,1,L2), (1,2,C), (2,3,L1)]
starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L1), (1,3,L1), (2,3,L1)]
#coupled_oscillators = [(0,1,C), (0,1,L1), (1,2,Cg), (2,0,C), (2,0,L1)]
coupled_oscillators = [(0,1,L1), (1,2,C), (2,0,L1), (0,1,C), (2,0,C)]

cr = Circuit(coupled_oscillators)






In [3]:
# Calculate omega_2B 
E_2B = cr.omega_2B
print(f"The matrix expression for omega_2B is:\n{E_2B}")

# Calculate omega
E = cr.omega_symplectic
print(f"The matrix expression for omega is:\n{cr.omega_symplectic}")
print(f"The matrix variable change for omega is:\n{cr.symplectic_basis_change}")
print(f"The determinant of matrix omega is:\n{np.linalg.det(E)}")

The matrix expression for omega_2B is:
[[ 0.   0.   0.   0.   0.  -0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.5]
 [ 0.5  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.5  0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -0.5  0.   0.   0.   0.   0. ]]
The matrix expression for omega is:
[[ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [-1. -0.  0.  0.]
 [-0. -1.  0.  0.]]
The matrix variable change for omega is:
[[ 1.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00 -5.94603558e-01  0.00000000e+00 -8.39456067e-17
   7.07106781e-01]
 [ 0.00000000e+00  5.94603558e-01 -0.00000000e+00 -2.05343847e-16
   7.07106781e-01]
 [ 0.00000000e+00 -0.

In [4]:
np.set_printoptions(precision=3)

# Calculate the Hamiltonian matrix before the variable change
Total_energy_2B = cr.Total_energy_2B
print(f"The matrix expression for the H before the variable change is:\n{Total_energy_2B}")

# Calculate the Hamiltonian matrix in the same basis as E_canonical
Total_energy_symplectic_basis = cr.Total_energy_symplectic_basis
print(f"The matrix expression for the H in the same basis as E_canonical is:\n{Total_energy_symplectic_basis}")

# Calculate the final expression for the Hamiltonian matrix, hamiltonian_xi
hamiltonian = cr.hamiltonian
hamiltonian_prueba = hamiltonian.copy()

print(f"The final matrix expression for the H is:\n{hamiltonian}")



The matrix expression for the H before the variable change is:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
The matrix expression for the H in the same basis as E_canonical is:
[[ 1.000e+00  5.946e-01  0.000e+00 -2.053e-16  7.071e-01]
 [ 5.946e-01  1.061e+00  0.000e+00 -1.943e-16  4.204e-01]
 [ 0.000e+00  0.000e+00  1.000e+00 -8.409e-01 -1.590e-16]
 [-2.053e-16 -1.943e-16 -8.409e-01  1.414e+00 -8.233e-17]
 [ 7.071e-01  4.204e-01 -1.590e-16 -8.233e-17  1.500e+00]]
The final matrix expression for the H is:
[[ 6.667e-01  3.964e-01  7.496e-17 -1.665e-16]
 [ 3.964e-01  9.428e-01  4.457e-17 -1.712e-16]
 [ 7.496e-17  4.457e-17  1.000e+00 -8.409e-01]
 [-1.665e-16 -1.712e-16 -8.409e-01  1.414e+00]]


In [5]:
from scircuit.algebra import *

H_n, T = canonical_transformation_quadratic_hamiltonian(hamiltonian)

print("Canonical Hamiltonian")
print(H_n)

print("Basis change matrix, T")
print(T)


Canonical Hamiltonian
[[ 5.774e-01 -1.477e-16  8.571e-18  1.611e-16]
 [-1.477e-16  1.000e+00 -2.661e-16  1.198e-17]
 [ 8.571e-18 -3.910e-16  5.774e-01 -3.275e-16]
 [ 1.961e-16  1.198e-17 -3.275e-16  1.000e+00]]
Basis change matrix, T
[[-9.306e-01  1.900e-16 -1.056e-17 -7.071e-01]
 [ 8.273e-16  0.000e+00 -7.070e-17  1.189e+00]
 [ 0.000e+00 -6.375e-16 -1.075e+00  6.010e-16]
 [-8.447e-17 -8.409e-01 -6.389e-01  4.080e-16]]


In [6]:
hamiltonian2 = np.block([[hamiltonian[2:,2:], np.zeros((2,2))],[np.zeros((2,2)), hamiltonian[:2, :2]]])
H_n, T = canonical_transformation_quadratic_hamiltonian(hamiltonian2)

print("Canonical Hamiltonian")
print(H_n)

print("Basis change matrix, T")
print(T)

Canonical Hamiltonian
[[ 5.774e-01 -4.609e-17 -6.179e-18 -4.333e-16]
 [-4.609e-17  1.000e+00  2.239e-16 -1.765e-16]
 [-6.179e-18  2.750e-16  5.774e-01 -1.956e-16]
 [-2.920e-16 -1.765e-16 -1.956e-16  1.000e+00]]
Basis change matrix, T
[[ 0.000e+00 -4.028e-16 -1.075e+00 -7.002e-17]
 [ 6.845e-17 -8.409e-01 -6.389e-01  1.067e-16]
 [ 9.306e-01  5.691e-17 -1.749e-16  7.071e-01]
 [-2.617e-16  0.000e+00  2.773e-16 -1.189e+00]]
