In [11]:
from scircuit import *
import numpy as np

In [12]:
#Define the circuit
C = Capacitor(value = 4, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
L2 = Inductor(value = 2, unit = 'GHz')
L3 = Inductor(value = 3, unit = 'GHz')
elements1 = [(0,1,C), (0,1,L1)] 
elements2 = [(0,2,C), (0,1,L1), (1,2,L2)] 
elements3 = [(0,2,C), (0,2,L1), (0,1,L2), (1,2,L3)]
elements4 = [(0,1,C), (0,1,L1), (0,1,L2)] 
starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L1), (1,3,L1), (2,3,L1)]

cr = Circuit(elements3)

print(cr.E_symplectic)
print(cr.symplectic_basis_change)


[(1.4142135623730943, array([ 1.344e-16, -1.208e-16,  8.409e-01,  0.000e+00]), array([0.595, 0.595, 0.   , 0.   ]))]
par
[[ 0.  1.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.344e-16  5.946e-01  7.071e-01  0.000e+00]
 [-1.208e-16  5.946e-01 -7.071e-01  0.000e+00]
 [ 8.409e-01  0.000e+00 -1.590e-16  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]


In [13]:
# Calculate omega_2B 
E_2B = cr.E_2B
print(f"The matrix expression for omega_2B is:\n{E_2B}")

# Calculate omega
E = cr.E_symplectic
print(f"The matrix expression for omega is:\n{cr.E_symplectic}")
print(f"The matrix variable change for omega is:\n{cr.symplectic_basis_change}")
print(f"The determinant of matrix omega is:\n{np.linalg.det(E)}")

The matrix expression for omega_2B is:
[[ 0.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.  -0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.5]
 [-0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.5  0.   0.   0.   0. ]]
The matrix expression for omega is:
[[ 0.  1.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
The matrix variable change for omega is:
[[ 1.344e-16  5.946e-01  7.071e-01  0.000e+00]
 [-1.208e-16  5.946e-01 -7.071e-01  0.000e+00]
 [ 8.409e-01  0.000e+00 -1.590e-16  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
The determinant of matrix omega is:
0.0


In [14]:
np.set_printoptions(precision=3)

# Calculate the Hamiltonian matrix before the variable change
Total_energy_2B = cr.Total_energy_2B
print(f"The matrix expression for the H before the variable change is:\n{Total_energy_2B}")

# Calculate the Hamiltonian matrix in the same basis as E_canonical
Total_energy_symplectic_basis = cr.Total_energy_symplectic_basis
print(f"The matrix expression for the H in the same basis as E_canonical is:\n{Total_energy_symplectic_basis}")

# Calculate the final expression for the Hamiltonian matrix, hamiltonian_xi
hamiltonian = cr.hamiltonian
print(f"The final matrix expression for the H is:\n{hamiltonian}")



The matrix expression for the H before the variable change is:
[[4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3.]]
The matrix expression for the H in the same basis as E_canonical is:
[[ 2.828e+00  6.458e-17 -2.523e+00]
 [ 6.458e-17  5.657e+00  0.000e+00]
 [-2.523e+00  0.000e+00  5.000e+00]]
The final matrix expression for the H is:
[[1.556e+00 6.458e-17]
 [6.458e-17 5.657e+00]]
