In [1]:
from scircuit import *
import numpy as np

In [ ]:
#Define the circuit
C = Capacitor(value = 1, unit='GHz')
Cg = Capacitor(value = 1, unit='GHz')
L1 = Inductor(value = 1, unit = 'GHz')
L2 = Inductor(value = 2, unit = 'GHz')
L3 = Inductor(value = 3, unit = 'GHz')
elements1 = [(0,1,C), (0,1,L1)] 
elements2 = [(0,2,C), (0,1,L1), (1,2,L2)] 
elements3 = [(0,2,C), (0,2,L1), (0,1,L2), (1,2,L3)]
elements4 = [(0,1,C), (0,1,L1), (0,1,L2)] 
elements5 = [(0,3,C), (0,3,L1), (0,1,L2), (1,2,C), (2,3,L1)]
starcircuit = [(0,1,C), (1,2,C), (2,0,C), (0,3,L1), (1,3,L1), (2,3,L1)]
#coupled_oscillators = [(0,1,C), (0,1,L1), (1,2,Cg), (2,0,C), (2,0,L1)]
coupled_oscillators = [(0,1,L1), (1,2,C), (2,0,L1), (0,1,C), (2,0,C)]

cr = Circuit(starcircuit)






In [3]:
# Calculate omega_2B 
E_2B = cr.omega_2B
print(f"The matrix expression for omega_2B is:\n{E_2B}")

# Calculate omega
E = cr.omega_symplectic
print(f"The matrix expression for omega is:\n{cr.omega_symplectic}")
print(f"The matrix variable change for omega is:\n{cr.symplectic_basis_change}")
print(f"The determinant of matrix omega is:\n{np.linalg.det(E)}")

The matrix expression for omega_2B is:
[[ 0.   0.   0.   0.   0.   0.   0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.  -0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5]
 [-0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.5  0.   0.   0.   0.   0.   0. ]]
The matrix expression for omega is:
[[ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [-1. -0.  0.  0.]
 [-0. -1.  0.  0.]]
The matrix variable change for omega is:
[[-0.00000000e+00  0.00000000e+00  0.00000000e+00 

In [4]:
np.set_printoptions(precision=3)

# Calculate the Hamiltonian matrix before the variable change
Total_energy_2B = cr.Total_energy_2B
print(f"The matrix expression for the H before the variable change is:\n{Total_energy_2B}")

# Calculate the Hamiltonian matrix in the same basis as E_canonical
Total_energy_symplectic_basis = cr.Total_energy_symplectic_basis
print(f"The matrix expression for the H in the same basis as E_canonical is:\n{Total_energy_symplectic_basis}")

# Calculate the final expression for the Hamiltonian matrix, hamiltonian_xi
hamiltonian = cr.hamiltonian
hamiltonian_prueba = hamiltonian.copy()

print(f"The final matrix expression for the H is:\n{hamiltonian}")



The matrix expression for the H before the variable change is:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
The matrix expression for the H in the same basis as E_canonical is:
[[ 1.618e+00  4.261e-16 -3.897e-16  1.391e-16  1.751e+00 -8.497e-17]
 [ 5.135e-16  6.180e-01 -4.174e-17  1.486e-17 -2.554e-01  3.297e-17]
 [-3.897e-16 -4.174e-17  1.618e+00  4.419e-16 -5.229e-16 -1.751e+00]
 [ 1.391e-16  1.486e-17  1.850e-16  6.180e-01  1.991e-16 -2.554e-01]
 [ 1.751e+00 -2.554e-01 -5.229e-16  1.991e-16  3.000e+00  0.000e+00]
 [-8.497e-17  3.297e-17 -1.751e+00 -2.554e-01  0.000e+

In [5]:
from scircuit.algebra import *

canonical_transformation_quadratic_hamiltonian(hamiltonian)


The initial Hmailtonian:
[[ 5.963e-01  1.491e-01 -1.342e-16  1.573e-17]
 [ 1.491e-01  5.963e-01 -6.702e-17  3.462e-17]
 [-1.342e-16 -6.702e-17  5.963e-01 -1.491e-01]
 [ 1.573e-17  3.462e-17 -1.491e-01  5.963e-01]]
The normal Hmailtonian:
[[ 5.774e-01  2.408e-16 -7.630e-17  5.576e-17]
 [ 1.722e-16  5.774e-01  1.891e-16  1.900e-16]
 [-3.549e-17  3.408e-17  5.774e-01 -3.295e-16]
 [ 1.081e-16  1.958e-16 -9.182e-17  5.774e-01]]
The normal form transfromation matrix T:
[[-0.992 -0.212 -0.042 -0.04 ]
 [ 0.11   0.785  0.168 -0.613]
 [ 0.     0.2   -0.996 -0.016]
 [-0.162  0.644 -0.142  0.756]]
The eigenvalues of K
[1.236e-16+0.577j 1.320e-17+0.577j]
The eigenvectors of K
[[-0.702-0.03j  -0.15 -0.028j]
 [ 0.078+0.119j  0.555-0.434j]
 [ 0.   -0.704j  0.141-0.012j]
 [-0.115-0.101j  0.455+0.535j]]
The product T.T @ J @ T, that must be J:
[[ 8.566e-19  4.996e-16  1.000e+00  4.756e-16]
 [-5.004e-16 -6.258e-17  1.993e-16  1.000e+00]
 [-1.000e+00 -1.765e-16 -6.979e-19  9.026e-18]
 [-4.916e-16 -1.000e+