In [15]:
from scircuit import *
import numpy as np
from sympy import Matrix


In [16]:
#Define the circuit
C = Capacitor(value = 1, unit='GHz')
L = Inductor(value = 1, unit = 'GHz')
elements1 = [(0,1,C), (0,1,L)] # Kernel is the same by both methods
elements2 = [(0,1,C), (1,2,L), (2,3,L), (3,0,L)]
elements3 = [(0,1,C), (0,1,L), (1,2,L), (2,3,L), (3,0,L)] # Kernel is not the same by both methods
cr = Circuit(elements3)


In [17]:
# Calculate Kirchhoff matrix (F) 
F = cr.F 

# Calculate kernel matrix (K) using K = [[Floop.T, 0],[0, Fcut.T]]
K = cr.K

# Calculate kernel using nullspace function 
F_sym = Matrix(F)
kernel_sym = F_sym.nullspace()

no_rows = len(kernel_sym[0])
no_columns = len(kernel_sym)
kernel = np.zeros((no_rows, no_columns))

for ii in range (no_rows): 
    for jj in range (no_columns) :
        kernel[ii,jj] = kernel_sym[jj][ii]

# Print both kernel matrixs and see what happend
print(f"Kernel matrix using F expression:\n{K}")
print(f"Kernel matrix using nullspace function:\n{kernel}")



Kernel matrix using F expression:
[[-0.  1.  0.  0.  0.]
 [-0.  1.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0. -1. -1. -1.]]
Kernel matrix using nullspace function:
[[ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1. -1. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [18]:
# Print results of F@K 
print(f"F times kernel matrix using F expression:\n{F@K}")
print(f"F times kernel matrix using nullspace function:\n{F@kernel}")


F times kernel matrix using F expression:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
F times kernel matrix using nullspace function:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
# (dq,dphi) = K (dQ, dPHI) -> (dQ, dPHI) = K^(-1) (dq,dphi)

K_inv = np.linalg.pinv(K)
print(f"The generalized inverse of K is:\n{K_inv}")



The generalized inverse of K is:
[[ 1.42857143e-01  1.42857143e-01 -4.28571429e-01  5.71428571e-01
   1.42857143e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.85714286e-01  2.85714286e-01  1.42857143e-01  1.42857143e-01
   2.85714286e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 3.52344610e-17 -4.71316991e-17  2.83146925e-17  2.83146925e-17
  -1.64174544e-17  7.14285714e-01 -2.85714286e-01 -1.42857143e-01
  -1.42857143e-01 -2.85714286e-01]
 [-4.88138198e-17  6.52962526e-17 -3.92271729e-17 -3.92271729e-17
   2.27447401e-17 -2.85714286e-01  7.14285714e-01 -1.42857143e-01
  -1.42857143e-01 -2.85714286e-01]
 [-2.16551022e-17  2.89671456e-17 -1.74022120e-17 -1.74022120e-17
   1.00901686e-17 -1.42857143e-01 -1.42857143e-01  4.28571429e-01
   4.28571429e-01 -1.42857143e-01]]


In [20]:
# Calculate omega_2B 

omega_2B = cr.omega_2B
print(f"The matrix expression for omega_2B is:\n{omega_2B}")

The matrix expression for omega_2B is:
[[ 0.   0.   0.   0.   0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.  -0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5]
 [-0.5  0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.5  0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0.   0.   0.   0.   0. ]]


In [21]:
# Calculate omega_alpha_beta

omega_alpha_beta = cr.omega_alpha_beta
print(f"The matrix expression for omega_alpha_beta is:\n{omega_alpha_beta}")

The matrix expression for omega_alpha_beta is:
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
